table 'DAX Measures'
	lineageTag: e8f7a110-755a-400a-9d4d-f1d4465b2276

	measure '# Total Matches Played' = DISTINCTCOUNT(fact_matches[match_id])
		formatString: 0
		displayFolder: 1_Matches\#
		lineageTag: b59566d6-95c7-43b1-af89-c915afb12943

	measure '# Home Matches Played' =
			
			CALCULATE(
			    DISTINCTCOUNT(fact_matches[match_id]),
			    fact_matches[home_away] = "H"
			)
		formatString: 0
		displayFolder: 1_Matches\#
		lineageTag: 5e504401-dcf2-40cb-b00a-76ec690034e4

	measure '# Away Matches Played' =
			
			CALCULATE(
			    DISTINCTCOUNT(fact_matches[match_id]),
			    fact_matches[home_away] = "A"
			)
		formatString: 0
		displayFolder: 1_Matches\#
		lineageTag: 3e2db747-645f-415e-a89b-28ce5fa7bd72

	measure '# Won Matches' =
			
			CALCULATE(
			    DISTINCTCOUNT(fact_matches[match_id]),
			    fact_matches[result] = "W"
			)
		formatString: 0
		displayFolder: 1_Matches\#
		lineageTag: 98f660e4-1774-4cc1-8430-69d9b4ef1752

	measure '# Lost Matches' =
			
			CALCULATE(
			    DISTINCTCOUNT(fact_matches[match_id]),
			    fact_matches[result] = "L"
			)
		formatString: 0
		displayFolder: 1_Matches\#
		lineageTag: 9fee0d5a-e271-4a4a-88f1-3c1cd2aa23e5

	measure '# Draw Matches' =
			
			CALCULATE(
			    DISTINCTCOUNT(fact_matches[match_id]),
			    fact_matches[result] = "D"
			)
		formatString: 0
		displayFolder: 1_Matches\#
		lineageTag: d6c07e37-d5d7-4599-8676-606dbb2b944f

	measure '# Goals Scored' =
			
			SUM(fact_matches[goals_for])
		formatString: 0
		displayFolder: 1_Matches\#
		lineageTag: 29f38175-f544-4c2c-bb72-7338b9f6263a

	measure '# Goals Conceded' =
			
			SUM(fact_matches[goals_against])
		formatString: 0
		displayFolder: 1_Matches\#
		lineageTag: 4b22929d-4e71-45e3-946a-43da302f39f5

	measure '# Goal Difference' = [# Goals Scored] - [# Goals Conceded]
		formatString: 0
		displayFolder: 1_Matches\#
		lineageTag: 20883732-8e6b-487a-aa55-6613125da5d2

	measure '# Clean Sheets' =
			
			CALCULATE(
			    DISTINCTCOUNT(fact_matches[match_id]),
			    fact_matches[goals_against] = 0
			)
		formatString: 0
		displayFolder: 1_Matches\#
		lineageTag: b21a4841-e233-4114-83b3-740d891b9328

	measure '% Win Rate' = ```
			
			DIVIDE(
			    [# Won Matches],
			    [# Total Matches Played], 
			    BLANK()
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1_Matches\%
		lineageTag: 09125640-1b93-4f9e-b774-62453d282f11

	measure '% Home Win Rate' =
			
			CALCULATE(
			    [% Win Rate],
			    fact_matches[home_away] = "H"
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1_Matches\%
		lineageTag: 1366751e-e738-410f-9161-c147479fbda9

	measure '% Away Win Rate' =
			
			CALCULATE(
			    [% Win Rate],
			    fact_matches[home_away] = "A"
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1_Matches\%
		lineageTag: 8aa79186-d0e1-4539-a9f0-7c2efd048bde

	measure 'REF Current Season' = MAX(dim_season[season_label])
		displayFolder: 0_General
		lineageTag: da4d1dcd-a456-4e85-ae9c-3aa0d13ff28d

	measure '$ Total Revenue (£)' =
			
			CALCULATE(
			    SUM(fact_financials[amount_gbp]),
			    fact_financials[type] = "Revenue"
			)
		formatString: "£"#,0;-"£"#,0;"£"#,0
		displayFolder: 2_Financials\$\£
		lineageTag: 17dc923f-42a1-43e7-ad5e-872396fed438

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure '$ Total Revenue (€)' =
			
			CALCULATE(
			    SUM(fact_financials[amount_eur]),
			    fact_financials[type] = "Revenue"
			)
		formatString: 0
		displayFolder: 2_Financials\$\€
		lineageTag: 9da216d3-a117-457f-81f8-ea03604b93a2

	measure '$ Total Cost (£)' =
			
			CALCULATE(
			    SUM(fact_financials[amount_gbp]),
			    fact_financials[type] = "Cost"
			)
		formatString: #,0
		displayFolder: 2_Financials\$\£
		lineageTag: c95e3756-1782-4149-9f96-dd77819db554

	measure '$ Total Cost (€)' =
			
			CALCULATE(
			    SUM(fact_financials[amount_eur]),
			    fact_financials[type] = "Cost"
			)
		formatString: 0
		displayFolder: 2_Financials\$\€
		lineageTag: 8e9395d1-8312-4166-b8b2-509a39db789f

	measure '$ Net Profit/Loss (£)' = [$ Total Revenue (£)] - [$ Total Cost (£)]
		formatString: #,0
		displayFolder: 2_Financials\$\£
		lineageTag: 4e41ee8f-ea41-480b-b029-45e2e03f24c9

	measure '$ Net Profit/Loss (€)' = [$ Total Revenue (€)] - [$ Total Cost (€)]
		formatString: #,0
		displayFolder: 2_Financials\$\€
		lineageTag: c9303aa3-6a0c-4234-9530-ddd22f94915b

	measure '$ Matchday Revenue (£)' = SUM(fact_matches[matchday_revenue_gbp])
		formatString: #,0
		displayFolder: 2_Financials\$\£
		lineageTag: fedede48-5f54-45ba-bc3d-30b8d487f87e

	measure '# Avg Goals Scored' = DIVIDE([# Goals Scored], [# Total Matches Played],0)
		displayFolder: 1_Matches\#
		lineageTag: 0b686cce-bb62-48f0-9a8a-404f89aa30fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Avg Goals Conceded' = ```
			DIVIDE([# Goals Conceded], [# Total Matches Played],0) 
			```
		displayFolder: 1_Matches\#
		lineageTag: fa52135d-9c36-4c1d-9386-49cef46a8e2d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Clean Sheet Rate' =
			
			DIVIDE([# Clean Sheets], [# Total Matches Played], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1_Matches\%
		lineageTag: d5a400d4-a75d-4353-9758-3dccea6f6a53

	measure '# PL Matches Played' = ```
			
			CALCULATE(
			    [# Total Matches Played], 
			    fact_matches[competition_id] = "C1"
			)
			```
		formatString: 0
		displayFolder: 1_Matches\#
		lineageTag: 50019525-8e1d-4425-9833-a45e5a34bec8

	measure '# PL Points' =
			
			// Premier League is C1 //
			CALCULATE(
			    SUMX(
			        fact_matches,
			        SWITCH(fact_matches[result],
			            "W", 3,
			            "D", 1,
			            0
			        )
			    ),
			    fact_matches[competition_id] = "C1"
			)
		formatString: 0
		displayFolder: 1_Matches\#
		lineageTag: b6693aa4-f628-4444-ab4b-07e6f0edd39c

	measure '% PL Win Rate' = ```
			
			DIVIDE(
			    CALCULATE(
			        [# Won Matches], 
			        fact_matches[competition_id] = "C1"
			        ),
			    [# PL Matches Played],
			    0
			)
			```
		displayFolder: 1_Matches\%
		lineageTag: edbb3586-73d1-4597-a7c5-6f4fb2938374

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Total Home Attendance' =
			
			CALCULATE(
			    SUM(fact_matches[attendance]),
			    fact_matches[home_away] = "H"
			)
		formatString: 0
		displayFolder: 1_Matches\#
		lineageTag: 2186cf28-f63d-4534-99f4-db0517e9fd3d

	measure '# Avg Home Attendance' =
			
			CALCULATE(
			    AVERAGE(fact_matches[attendance]),
			    fact_matches[home_away] = "H",
			    fact_matches[attendance] > 0
			)
		displayFolder: 1_Matches\#
		lineageTag: 528895a1-ed0c-4057-bcc8-5b20b539241c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '$ Avg Matchday Revenue per Home Game (£)' =
			
			DIVIDE(
			    [$ Matchday Revenue (£)],
			    [# Home Matches Played],
			    0
			)
		displayFolder: 2_Financials\$\£
		lineageTag: 449dde46-a996-420e-8599-0eea1abeac29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '$ Broadcast Revenue (£)' =
			
			CALCULATE(
			    SUM(fact_financials[amount_gbp]),
			    fact_financials[type] = "Revenue",
			    fact_financials[category] = "Revenue",
			    fact_financials[subcategory] = "Broadcast"
			)
		formatString: #,0
		displayFolder: 2_Financials\$\£
		lineageTag: 868d0a6b-f861-4e3d-8443-616d9d9188b9

	measure '$ Commercial Revenue (£)' = ```
			
			CALCULATE(
			    SUM(fact_financials[amount_gbp]),
			    fact_financials[type] = "Revenue",
			    fact_financials[subcategory] = "Commercial"
			) 
			```
		formatString: #,0
		displayFolder: 2_Financials\$\£
		lineageTag: 910eee0e-4c4a-4add-af2a-5f103aff1548

	measure '$ Matchday Revenue 2 (£)' =
			
			CALCULATE(
			    SUM(fact_financials[amount_gbp]),
			    fact_financials[type] = "Revenue",
			    fact_financials[subcategory] = "Matchday"
			)
		formatString: #,0
		displayFolder: 2_Financials\$\£
		lineageTag: f7cbeb7f-f078-409e-810c-52b8a496ce95

	measure '$ Player Sales Revenue (£)' =
			
			CALCULATE(
			    SUM(fact_financials[amount_gbp]),
			    fact_financials[type] = "Revenue",
			    fact_financials[subcategory] = "Player Sales"
			)
		formatString: 0
		displayFolder: 2_Financials\$\£
		lineageTag: 963cc3e3-5e84-4ad9-a210-24fb96282816

	measure '% Broadcast Revenue of Total' =
			
			DIVIDE([$ Broadcast Revenue (£)], [$ Total Revenue (£)], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 2_Financials\%\£
		lineageTag: 38423458-ffed-43fb-9f62-376df88f573f

	measure '% Commercial Revenue of Total' =
			
			DIVIDE([$ Commercial Revenue (£)], [$ Total Revenue (£)], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 2_Financials\%\£
		lineageTag: b5eccc08-0442-43ac-8028-2289183b99d8

	measure '% Matchday Revenue of Total' =
			
			DIVIDE([$ Matchday Revenue 2 (£)], [$ Total Revenue (£)], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 2_Financials\%\£
		lineageTag: ae8abad1-86d1-49ee-a0ed-1ca7f72f563f

	measure '$ Total Player Wage Costs (£)' =
			
			CALCULATE(
			    SUM(fact_financials[amount_gbp]),
			    fact_financials[subcategory] = "Wages - Players"
			)
		formatString: 0
		displayFolder: 2_Financials\$\£
		lineageTag: 72088f55-891d-47a9-998c-f45c0b19e846

	measure '$ Total Staff Wage Costs (£)' = ```
			
			CALCULATE(
			    SUM(fact_financials[amount_gbp]),
			    fact_financials[subcategory] = "Wages - Staff"
			) 
			```
		formatString: 0
		displayFolder: 2_Financials\$\£
		lineageTag: f82b8843-99be-4e37-bf68-690f9058e5ff

	measure '$ Total Transfer Amortization Costs (£)' = ```
			
			CALCULATE(
			    SUM(fact_financials[amount_gbp]),
			    fact_financials[subcategory] = "Transfer Amortisation"
			) 
			```
		formatString: 0
		displayFolder: 2_Financials\$\£
		lineageTag: 6fcfaf15-8d97-41a1-8f20-ee8b109f2927

	measure '$ Total Agent Fees Costs (£)' = ```
			
			CALCULATE(
			    SUM(fact_financials[amount_gbp]),
			    fact_financials[subcategory] = "Agent Fees"
			)  
			```
		formatString: 0
		displayFolder: 2_Financials\$\£
		lineageTag: 97a6d7b2-b07d-4576-aaea-1d48e5544a08

	measure '% Wage to Revenue Ratio' =
			
			DIVIDE([$ Total Player Wage Costs (£)], [$ Total Revenue (£)], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 2_Financials\%\£
		lineageTag: f64e162b-1ef4-4568-893f-7067533d2135

	measure '% Revenue YoY Growth' =
			
			VAR CurrentRevenue = [$ Total Revenue (£)]
			VAR PreviousRevenue =
			    CALCULATE(
			        [$ Total Revenue (£)],
			        PREVIOUSYEAR(Calendar[Date])
			    )
			RETURN
			    DIVIDE(CurrentRevenue - PreviousRevenue, PreviousRevenue, 0)
		displayFolder: 2_Financials\%\£
		lineageTag: c5477e77-e093-4487-b717-72063ffd67d9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '$ Total Transfer Spend (£)' =
			
			CALCULATE(
			    SUM(fact_transfers[transfer_fee_gbp]),
			    fact_transfers[direction] = "IN",
			    fact_transfers[loan] = FALSE()
			)
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		displayFolder: 3_Transfers\$
		lineageTag: 9e44bb38-5e13-4cf1-aa24-c3bed6463904

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure '$ Total Transfer Income (£)' =
			
			CALCULATE(
			    SUM(fact_transfers[transfer_fee_gbp]),
			    fact_transfers[direction] = "OUT",
			    fact_transfers[loan] = FALSE()
			)
		formatString: 0
		displayFolder: 3_Transfers\$
		lineageTag: a4d37261-d412-4711-bf14-597663889067

	measure '$ Net Transfer Spend (£)' =
			
			[$ Total Transfer Spend (£)] - [$ Total Transfer Income (£)]
		formatString: 0
		displayFolder: 3_Transfers\$
		lineageTag: 1a65f22b-95d1-4c7f-a955-aa9f21916533

	measure '$ Avg Transfer Fee IN (£)' =
			
			CALCULATE(
			    AVERAGE(fact_transfers[transfer_fee_gbp]),
			    fact_transfers[direction] = "IN",
			    fact_transfers[loan] = FALSE(),
			    fact_transfers[transfer_fee_gbp] > 0
			)
		displayFolder: 3_Transfers\$
		lineageTag: 9789d4d7-0bcc-48f4-874a-76b7ddc8c27a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Total Transfers IN' =
			
			CALCULATE(
			    COUNTROWS(fact_transfers),
			    fact_transfers[direction] = "IN"
			)
		formatString: 0
		displayFolder: 3_Transfers\#
		lineageTag: 93cd6541-73dd-442a-81fe-4c995bf6b972

	measure '# Total Transfers OUT' = ```
			
			CALCULATE(
			    COUNTROWS(fact_transfers),
			    fact_transfers[direction] = "OUT"
			) 
			```
		formatString: 0
		displayFolder: 3_Transfers\#
		lineageTag: 400eadd0-beab-4678-b7ca-ada97e2b1648

	measure '# Total Loans' =
			
			CALCULATE(
			    COUNTROWS(fact_transfers),
			    fact_transfers[loan] = TRUE()
			)
		formatString: 0
		displayFolder: 3_Transfers\#
		lineageTag: d3ef0901-ba54-4d58-b490-9d75a7068a73

	measure '# Avg Age of Signings' =
			
			CALCULATE(
			    AVERAGE(fact_transfers[age_at_transfer]),
			    fact_transfers[direction] = "IN",
			    fact_transfers[loan] = FALSE()
			)
		displayFolder: 3_Transfers\#
		lineageTag: 28db20d1-f06e-4604-ac1d-a3b6f47d4d24

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '$ Total Annual Wage Bill (£)' =
			
			SUM(fact_player_wages[annual_wage_gbp])
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		displayFolder: 4_Wages\$
		lineageTag: 39190125-d454-4ce2-8718-8013f7cb1b6a

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure '$ Total Weekly Wage Bill (£)' =
			
			SUM(fact_player_wages[weekly_wage_gbp])
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		displayFolder: 4_Wages\$
		lineageTag: 0b8d872c-aefd-439c-bd20-4acfc086ba42

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure '$ Avg Weekly Wage Bill (£)' =
			
			AVERAGE(fact_player_wages[weekly_wage_gbp])
		displayFolder: 4_Wages\$
		lineageTag: 7c19eb07-2b97-41e2-910f-8b9fbd78507c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '$ Highest Paid Player (£)' = ```
			
			CALCULATE(
			    FIRSTNONBLANK(fact_player_wages[player_name], 1),
			    TOPN(
			        1, 
			        fact_player_wages, 
			        fact_player_wages[weekly_wage_gbp], 
			        DESC
			    )
			)
			```
		displayFolder: 4_Wages\$
		lineageTag: 0f987f56-8550-4bdd-9692-0430d5e3655d

	measure '$ Total Signing Bonuses (£)' = ```
			
			SUM(fact_player_wages[signing_bonus_gbp]) 
			```
		formatString: 0
		displayFolder: 4_Wages\$
		lineageTag: 21af640e-5761-4cbc-9dc6-89df8c978f70

	measure '$ Total Performance Bonuses (£)' =
			
			SUM(fact_player_wages[performance_bonus_gbp])
		formatString: 0
		displayFolder: 4_Wages\$
		lineageTag: 062d0915-3566-458a-857e-1aaef79fc35f

	measure '$ Total Agent Fees Wages (£)' =
			
			SUM(fact_player_wages[agent_fee_gbp])
		formatString: 0
		displayFolder: 4_Wages\$
		lineageTag: f75fd128-9dcc-4a4e-a30d-588e38370e52

	measure '$ Total Bonus Paid (£)' =
			
			[$ Total Signing Bonuses (£)] + [$ Total Performance Bonuses (£)]
		formatString: 0
		displayFolder: 4_Wages\$
		lineageTag: a32c5fd6-4bdb-443f-bcc6-06054d5f2803

	measure '% Wage Bill YoY Change' = ```
			
			VAR CurrentWages = [$ Total Annual Wage Bill (£)]
			VAR PreviousWages =
			    CALCULATE(
			        [$ Total Annual Wage Bill (£)],
			        FILTER(
			            ALL(dim_season),
			            dim_season[season_id] = 
			                CALCULATE(
			                    MIN(dim_season[season_id]),
			                    ALLSELECTED(dim_season)
			                ) - 1
			        )
			    )
			RETURN
			    DIVIDE(CurrentWages - PreviousWages, PreviousWages, 0)
			```
		formatString: 0
		displayFolder: 4_Wages\%
		lineageTag: 24753fed-40e8-4658-a912-28a98782c625

	measure '$ Wage per Appearance (£)' =
			
			DIVIDE(
			    [$ Total Annual Wage Bill (£)],
			    CALCULATE(SUM(fact_player_performance[appearances])),
			    0
			)
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		displayFolder: 4_Wages\$
		lineageTag: 40dfe66f-2a93-48dc-aa2e-12c6bcd58e1b

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure '$ Squad Market Value (£)' =
			
			SUM(fact_player_valuations[market_value_gbp])
		formatString: "£"#,0;-"£"#,0;"£"#,0
		displayFolder: 5_Squad_Value\$
		lineageTag: 2c43e262-a578-4c15-a06d-894e9d209868

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure '$ Avg Player Market Value (£)' =
			
			AVERAGE(fact_player_valuations[market_value_gbp])
		displayFolder: 5_Squad_Value\$
		lineageTag: 4251eda7-8b0c-4f38-9388-c25b0e5949a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '$ Highest Player Market Value (£)' =
			
			MAX(fact_player_valuations[market_value_gbp])
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		displayFolder: 5_Squad_Value\$
		lineageTag: f2fd1d35-d75e-4942-9d97-8575f4390f18

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure '$ Most Valuable Player (£)' = ```
			
			CALCULATE(
			    FIRSTNONBLANK(fact_player_valuations[player_name], 1),
			    TOPN(
			        1, 
			        fact_player_valuations, 
			        fact_player_valuations[market_value_gbp], 
			        DESC
			    )
			)
			```
		displayFolder: 5_Squad_Value\$
		lineageTag: 98827e44-067c-4d82-a855-cc0a0e3a315a

	measure '$ Squad Value YoY Change (£)' = ```
			
			VAR CurrentValue = [$ Squad Market Value (£)]
			VAR PreviousValue =
			    CALCULATE(
			        [$ Squad Market Value (£)],
			        FILTER(
			            ALL(dim_season),
			            dim_season[season_id] = 
			                CALCULATE(MAX(dim_season[season_id]), ALLSELECTED(dim_season)) - 1
			        )
			    )
			RETURN
			    CurrentValue - PreviousValue
			```
		formatString: 0
		displayFolder: 5_Squad_Value\$
		lineageTag: fe71adf0-9322-4815-8f52-e159c4f9d891

	measure '% Squad Value YoY Change (£)' = ```
			
			VAR CurrentValue = [$ Squad Market Value (£)]
			VAR PreviousValue =
			    CALCULATE(
			        [$ Squad Market Value (£)],
			        FILTER(
			            ALL(dim_season),
			            dim_season[season_id] = 
			                CALCULATE(MAX(dim_season[season_id]), ALLSELECTED(dim_season)) - 1
			        )
			    )
			RETURN
			    DIVIDE(CurrentValue - PreviousValue, PreviousValue, 0) 
			```
		formatString: 0%;-0%;0%
		displayFolder: 5_Squad_Value\%
		lineageTag: dd00bc8e-44ea-47a0-bf1c-a906423ffbd6

	measure '$ Value vs Fee Ratio' =
			
			// Ratio: if > 1 the player is worth more than paid, if < 1 overpaid //
			DIVIDE(
			    CALCULATE(SUM(fact_player_valuations[market_value_gbp])),
			    CALCULATE(
			        SUM(fact_transfers[transfer_fee_gbp]),
			        fact_transfers[direction] = "IN",
			        fact_transfers[loan] = FALSE()
			    ),
			    0
			)
		displayFolder: 5_Squad_Value\$
		lineageTag: 3f3de45d-02a5-4009-966e-6aa19a9d4aec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Total Goals' =
			
			SUM(fact_player_performance[goals])
		formatString: 0
		displayFolder: 6_Performance\#
		lineageTag: 81cc3d8d-4005-4bf4-a1c4-89c143fed9b9

	measure '# Total Assists' =
			
			SUM(fact_player_performance[assists])
		formatString: 0
		displayFolder: 6_Performance\#
		lineageTag: 26cd3d07-535b-43ff-a13f-a13e9ca7e30a

	measure '# Total Goal Contributions' =
			
			[# Total Goals] + [# Total Assists]
		formatString: 0
		displayFolder: 6_Performance\#
		lineageTag: 56057833-51a6-4a00-8dfe-cdf88a422c6f

	measure '# Total Appearances' = ```
			
			SUM(fact_player_performance[appearances]) 
			```
		formatString: #,0
		displayFolder: 6_Performance\#
		lineageTag: 7c6888b9-0500-4ce0-b91a-8f3a55be4e4f

	measure '# Total Minutes Played' =
			
			SUM(fact_player_performance[minutes_played])
		formatString: 0
		displayFolder: 6_Performance\#
		lineageTag: 6788b2d8-445a-43c8-bf93-aa707f88612f

	measure '# Minutes per Goal' =
			
			DIVIDE(
			    [# Total Minutes Played],
			    [# Total Goals],
			    0
			)
		displayFolder: 6_Performance\#
		lineageTag: a1369fcf-427e-4adf-95a9-328d102d7053

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Minutes per Goal Contribution' =
			
			DIVIDE(
			    [# Total Minutes Played],
			    [# Total Goal Contributions],
			    0
			)
		displayFolder: 6_Performance\#
		lineageTag: fe512799-bbc5-4c9d-a7a1-95eeb68fcc20

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Avg Player Rating' = ```
			
			AVERAGE(fact_player_performance[rating_avg]) 
			```
		displayFolder: 6_Performance\#
		lineageTag: 3490793a-ea83-4b96-b15e-a50293431890

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'REF Top Scorer Name' = ```
			
			CALCULATE(
			    FIRSTNONBLANK(fact_player_performance[player_name], 1),
			    TOPN(
			        1, 
			        fact_player_performance, 
			        fact_player_performance[goals], 
			        DESC
			    )
			)
			```
		displayFolder: 6_Performance\#
		lineageTag: f7e1980d-f498-471a-9396-ec0d262526db

	measure '# Top Scorer Goals' =
			
			CALCULATE(
			    MAX(fact_player_performance[goals]),
			    ALLSELECTED(fact_player_performance)
			)
		formatString: 0
		displayFolder: 6_Performance\#
		lineageTag: 0dfc6f7d-be75-485a-9476-817caa0c5035

	measure '# Total Yellow Cards' =
			
			SUM(fact_player_performance[yellow_cards])
		formatString: 0
		displayFolder: 6_Performance\#
		lineageTag: c3a1bc88-86e4-4c51-a986-27f9eec1c1b8

	measure '# Total Red Cards' =
			
			SUM(fact_player_performance[red_cards])
		formatString: 0
		displayFolder: 6_Performance\#
		lineageTag: 668d5490-6d06-4cd2-a478-ca3776c9ea62

	measure '# Goals per 90 Minutes' =
			
			DIVIDE([# Total Goals], DIVIDE([# Total Minutes Played], 90, 0), 0)
		formatString: 0.00
		displayFolder: 6_Performance\#
		lineageTag: 8f714e7e-258b-48a2-bb04-a0f25ee06201

	measure '# Assists per 90 Minutes' =
			
			DIVIDE([# Total Assists], DIVIDE([# Total Minutes Played], 90, 0), 0)
		formatString: 0.00
		displayFolder: 6_Performance\#
		lineageTag: 37b64728-0556-408b-8478-3428f57aaab5

	measure '# Goal Contributions per 90' =
			
			DIVIDE([# Total Goal Contributions], DIVIDE([# Total Minutes Played], 90, 0), 0)
		formatString: 0.00
		displayFolder: 6_Performance\#
		lineageTag: 1f9c0535-5dce-4aac-9263-c27246f1b23c

	measure '% Avg Pass Accuracy' =
			
			AVERAGE(fact_player_performance[pass_accuracy_pct])
		formatString: 0.0
		displayFolder: 6_Performance\%
		lineageTag: b69a7088-a4fd-4394-86ac-fe6c9b964d58

	measure '# Players Tracked' =
			
			COUNTROWS(
			    DISTINCT(
			        UNION(
			            SELECTCOLUMNS(
			                fact_player_valuations,
			                "player_id", fact_player_valuations[player_id]
			            ),
			            SELECTCOLUMNS(
			                fact_player_performance,
			                "player_id", fact_player_performance[player_id]
			            )
			        )
			    )
			)
		formatString: 0
		displayFolder: 0_General
		lineageTag: c138175a-0d6f-4335-aba3-3c211319fd79

	measure '# Season Analyzed' = ```
			DISTINCTCOUNT(fact_financials[season_id]) 
			```
		formatString: 0
		displayFolder: 2_Financials\#
		lineageTag: 9dc1e752-c516-452b-87d4-d482c8b28c57

	measure '# Trophies Won' = COUNT(dim_season[trophies_won])
		formatString: 0
		displayFolder: 0_General
		lineageTag: cf218901-4568-4a71-9987-542e650d3d1a

	measure 'REF PL Position' = MAX(dim_season[pl_finish])
		displayFolder: 0_General
		lineageTag: 474cee4f-b446-42fe-94e7-83093cf6755d

	measure 'VIS HTML Match Snapshot' =
			
			VAR _CurrentStartYear = SELECTEDVALUE(dim_season[start_year])
			VAR _PrevStartYear = _CurrentStartYear - 1
			VAR _HasSingleSeason = NOT ISBLANK(_CurrentStartYear)
			
			VAR _Points = [# PL Points]
			VAR _PointsPY =
			    IF(
			        _HasSingleSeason,
			        CALCULATE(
			            [# PL Points],
			            REMOVEFILTERS(dim_season),
			            dim_season[start_year] = _PrevStartYear
			        )
			    )
			VAR _PointsG = DIVIDE(_Points - _PointsPY, _PointsPY)
			VAR _PointsClass = IF(ISBLANK(_PointsG) || _PointsG >= 0, "pos", "neg")
			VAR _PointsArrow = IF(ISBLANK(_PointsG), "•", IF(_PointsG >= 0, "↑", "↓"))
			VAR _PointsFmt = FORMAT(_Points, "#,##0")
			VAR _PointsPYFmt = IF(ISBLANK(_PointsPY), "—", FORMAT(_PointsPY, "#,##0"))
			VAR _PointsGFmt = IF(ISBLANK(_PointsG), "—", FORMAT(ABS(_PointsG), "0.0%"))
			
			VAR _Win = [% Win Rate]
			VAR _WinPY =
			    IF(
			        _HasSingleSeason,
			        CALCULATE(
			            [% Win Rate],
			            REMOVEFILTERS(dim_season),
			            dim_season[start_year] = _PrevStartYear
			        )
			    )
			VAR _WinDelta = _Win - _WinPY
			VAR _WinClass = IF(ISBLANK(_WinDelta) || _WinDelta >= 0, "pos", "neg")
			VAR _WinArrow = IF(ISBLANK(_WinDelta), "•", IF(_WinDelta >= 0, "↑", "↓"))
			VAR _WinFmt = FORMAT(_Win, "0.0%")
			VAR _WinPYFmt = IF(ISBLANK(_WinPY), "—", FORMAT(_WinPY, "0.0%"))
			VAR _WinGFmt = IF(ISBLANK(_WinDelta), "—", FORMAT(ABS(_WinDelta) * 100, "0.0") & " pp")
			VAR _HomeWinFmt = FORMAT([% Home Win Rate], "0.0%")
			VAR _AwayWinFmt = FORMAT([% Away Win Rate], "0.0%")
			
			VAR _GF = [# Goals Scored]
			VAR _GA = [# Goals Conceded]
			VAR _GD = [# Goal Difference]
			VAR _GDClass = IF(_GD >= 0, "pos", "neg")
			VAR _GDFmt = IF(_GD > 0, "+" & FORMAT(_GD, "#,##0"), FORMAT(_GD, "#,##0"))
			VAR _GoalsFmt = FORMAT(_GF, "#,##0") & " / " & FORMAT(_GA, "#,##0")
			VAR _AvgGoalsFmt = FORMAT([# Avg Goals Scored], "0.0") & " for · " & FORMAT([# Avg Goals Conceded], "0.0") & " against"
			
			VAR _Attendance = [# Avg Home Attendance]
			VAR _AttendancePY =
			    IF(
			        _HasSingleSeason,
			        CALCULATE(
			            [# Avg Home Attendance],
			            REMOVEFILTERS(dim_season),
			            dim_season[start_year] = _PrevStartYear
			        )
			    )
			VAR _AttendanceG = DIVIDE(_Attendance - _AttendancePY, _AttendancePY)
			VAR _AttendanceClass = IF(ISBLANK(_AttendanceG) || _AttendanceG >= 0, "pos", "neg")
			VAR _AttendanceArrow = IF(ISBLANK(_AttendanceG), "•", IF(_AttendanceG >= 0, "↑", "↓"))
			VAR _AttendanceFmt = FORMAT(_Attendance, "#,##0")
			VAR _AttendancePYFmt = IF(ISBLANK(_AttendancePY), "—", FORMAT(_AttendancePY, "#,##0"))
			VAR _AttendanceGFmt = IF(ISBLANK(_AttendanceG), "—", FORMAT(ABS(_AttendanceG), "0.0%"))
			RETURN
			"<style>
			.cv{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;width:100%;height:100%;font-family:'Segoe UI',sans-serif;padding:6px;box-sizing:border-box;}
			.ci{background:#141E30;border-radius:8px;border:1px solid #2c3b54;border-left:3px solid #D4AF37;padding:11px 12px;display:flex;flex-direction:column;justify-content:space-between;min-width:0;overflow:hidden;}
			.cl{color:#D4AF37;font-size:9px;text-transform:uppercase;letter-spacing:1.2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
			.cn{color:#fff;font-size:20px;font-weight:700;line-height:1.05;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}
			.cs{display:flex;align-items:center;gap:8px;color:#7FA4CF;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
			.cs b{color:#fff;font-weight:700;}
			.cf{display:flex;align-items:center;gap:7px;justify-content:flex-end;min-width:0;}
			.cp{font-size:10px;font-weight:700;padding:2px 7px;border-radius:99px;white-space:nowrap;}
			.pos{background:#052e16;border:1px solid #00A651;color:#4ade80;}
			.neg{background:#450a0a;border:1px solid #D62D20;color:#f87171;}
			.cy{font-size:10px;color:#7FA4CF;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
			</style>
			<div class=""cv"">
			  <div class=""ci""><div class=""cl"">PL Points</div><div class=""cn"">" & _PointsFmt & "</div><div class=""cf""><span class=""cp " & _PointsClass & """>" & _PointsArrow & " " & _PointsGFmt & "</span><span class=""cy"">vs PY: " & _PointsPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Win Rate</div><div class=""cn"">" & _WinFmt & "</div><div class=""cs""><span>H <b>" & _HomeWinFmt & "</b></span><span>A <b>" & _AwayWinFmt & "</b></span></div><div class=""cf""><span class=""cp " & _WinClass & """>" & _WinArrow & " " & _WinGFmt & "</span><span class=""cy"">vs PY: " & _WinPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Goals For / Against</div><div class=""cn"">" & _GoalsFmt & "</div><div class=""cs"">" & _AvgGoalsFmt & "</div><div class=""cf""><span class=""cp " & _GDClass & """>GD " & _GDFmt & "</span><span class=""cy"">scored / conceded</span></div></div>
			  <div class=""ci""><div class=""cl"">Avg Home Attendance</div><div class=""cn"">" & _AttendanceFmt & "</div><div class=""cf""><span class=""cp " & _AttendanceClass & """>" & _AttendanceArrow & " " & _AttendanceGFmt & "</span><span class=""cy"">vs PY: " & _AttendancePYFmt & "</span></div></div>
			</div>"
		displayFolder: 7_Visuals
		lineageTag: c92fbf50-4b0c-474e-889b-474c158d9d7c

	measure '% Draw Rate' = DIVIDE([# Draw Matches], [# Total Matches Played], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1_Matches\%
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567801

	measure '% Loss Rate' = DIVIDE([# Lost Matches], [# Total Matches Played], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1_Matches\%
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567802

	measure '# PL Points Previous Season' =
			
			CALCULATE(
			    [# PL Points],
			    FILTER(
			        ALL(dim_season),
			        dim_season[start_year] =
			            CALCULATE(MIN(dim_season[start_year]), ALLSELECTED(dim_season)) - 1
			    )
			)
		formatString: 0
		displayFolder: 4_Trends\#
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567803

	measure '# PL Points YoY Change' = [# PL Points] - [# PL Points Previous Season]
		formatString: 0
		displayFolder: 4_Trends\#
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567804

	measure '% PL Points YoY Change' = DIVIDE([# PL Points YoY Change], [# PL Points Previous Season], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 4_Trends\%
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567805

	measure '% Win Rate Previous Season' =
			
			CALCULATE(
			    [% Win Rate],
			    FILTER(
			        ALL(dim_season),
			        dim_season[start_year] =
			            CALCULATE(MIN(dim_season[start_year]), ALLSELECTED(dim_season)) - 1
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 4_Trends\%
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567806

	measure '% Win Rate YoY Change' = [% Win Rate] - [% Win Rate Previous Season]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 4_Trends\%
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567807

	measure '# Goals Scored Previous Season' =
			
			CALCULATE(
			    [# Goals Scored],
			    FILTER(
			        ALL(dim_season),
			        dim_season[start_year] =
			            CALCULATE(MIN(dim_season[start_year]), ALLSELECTED(dim_season)) - 1
			    )
			)
		formatString: 0
		displayFolder: 4_Trends\#
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567808

	measure '% Goals Scored YoY Change' =
			
			VAR Prev = [# Goals Scored Previous Season]
			RETURN DIVIDE([# Goals Scored] - Prev, Prev, 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 4_Trends\%
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567809

	measure '# Goals Conceded Previous Season' =
			
			CALCULATE(
			    [# Goals Conceded],
			    FILTER(
			        ALL(dim_season),
			        dim_season[start_year] =
			            CALCULATE(MIN(dim_season[start_year]), ALLSELECTED(dim_season)) - 1
			    )
			)
		formatString: 0
		displayFolder: 4_Trends\#
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567810

	measure '% Goals Conceded YoY Change' =
			
			VAR Prev = [# Goals Conceded Previous Season]
			RETURN DIVIDE([# Goals Conceded] - Prev, Prev, 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 4_Trends\%
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567811

	measure '$ Total Revenue YoY Change (£)' =
			
			VAR Prev = CALCULATE([$ Total Revenue (£)], PREVIOUSYEAR(Calendar[Date]))
			RETURN [$ Total Revenue (£)] - Prev
		formatString: 0
		displayFolder: 2_Financials\$\£
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567812

	measure '$ Total Cost YoY Change (£)' =
			
			VAR Prev = CALCULATE([$ Total Cost (£)], PREVIOUSYEAR(Calendar[Date]))
			RETURN [$ Total Cost (£)] - Prev
		formatString: 0
		displayFolder: 2_Financials\$\£
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567813

	measure '% Total Cost YoY Growth' =
			
			VAR CurrentY = [$ Total Cost (£)]
			VAR Prev    = CALCULATE([$ Total Cost (£)], PREVIOUSYEAR(Calendar[Date]))
			RETURN DIVIDE(CurrentY - Prev, Prev, 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 2_Financials\%\£
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567814

	measure '$ Revenue YTD (£)' = CALCULATE([$ Total Revenue (£)], DATESYTD(Calendar[Date]))
		formatString: 0
		displayFolder: 2_Financials\$\£
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567815

	measure '$ Cost YTD (£)' = CALCULATE([$ Total Cost (£)], DATESYTD(Calendar[Date]))
		formatString: 0
		displayFolder: 2_Financials\$\£
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567816

	measure '$ Revenue Previous Month (£)' = CALCULATE([$ Total Revenue (£)], DATEADD(Calendar[Date], -1, MONTH))
		formatString: 0
		displayFolder: 4_Trends\$
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567817

	measure '% Revenue MoM Growth' =
			
			VAR Prev = [$ Revenue Previous Month (£)]
			RETURN DIVIDE([$ Total Revenue (£)] - Prev, Prev, 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 4_Trends\%
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567818

	measure '# Goals Scored Previous Month' = CALCULATE([# Goals Scored], DATEADD(Calendar[Date], -1, MONTH))
		formatString: 0
		displayFolder: 4_Trends\#
		lineageTag: c3e5a712-8b9d-4f1e-a023-6b7c8d9e0f1b

	measure '% Goals Scored MoM Change' =
			
			VAR Prev = [# Goals Scored Previous Month]
			RETURN DIVIDE([# Goals Scored] - Prev, ABS(Prev), 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 4_Trends\%
		lineageTag: c3e5a712-8b9d-4f1e-a023-6b7c8d9e0f1c

	measure '# Won Matches Previous Month' = CALCULATE([# Won Matches], DATEADD(Calendar[Date], -1, MONTH))
		formatString: 0
		displayFolder: 4_Trends\#
		lineageTag: c3e5a712-8b9d-4f1e-a023-6b7c8d9e0f1d

	measure '% Win Rate MoM Change' = [% Win Rate] - CALCULATE([% Win Rate], DATEADD(Calendar[Date], -1, MONTH))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 4_Trends\%
		lineageTag: c3e5a712-8b9d-4f1e-a023-6b7c8d9e0f1e

	measure '$ Transfer Spend Previous Season (£)' =
			
			CALCULATE(
			    [$ Total Transfer Spend (£)],
			    FILTER(
			        ALL(dim_season),
			        dim_season[start_year] =
			            CALCULATE(MIN(dim_season[start_year]), ALLSELECTED(dim_season)) - 1
			    )
			)
		formatString: 0
		displayFolder: 3_Transfers\$
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567819

	measure '$ Transfer Spend YoY Change (£)' = [$ Total Transfer Spend (£)] - [$ Transfer Spend Previous Season (£)]
		formatString: 0
		displayFolder: 3_Transfers\$
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567820

	measure '% Transfer Spend YoY Change' =
			
			DIVIDE(
			    [$ Transfer Spend YoY Change (£)],
			    ABS([$ Transfer Spend Previous Season (£)]),
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 3_Transfers\%
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567821

	measure '$ Wage Bill Previous Season (£)' =
			
			CALCULATE(
			    [$ Total Annual Wage Bill (£)],
			    FILTER(
			        ALL(dim_season),
			        dim_season[start_year] =
			            CALCULATE(MIN(dim_season[start_year]), ALLSELECTED(dim_season)) - 1
			    )
			)
		formatString: 0
		displayFolder: 4_Wages\$
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567822

	measure '$ Wage Bill YoY Change (£)' = [$ Total Annual Wage Bill (£)] - [$ Wage Bill Previous Season (£)]
		formatString: 0
		displayFolder: 4_Wages\$
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567823

	measure 'VIS HTML Financial Snapshot' =
			
			VAR _PrevStartYear = CALCULATE(MIN(dim_season[start_year]), ALLSELECTED(dim_season)) - 1
			
			VAR _Rev = [$ Total Revenue (£)]
			VAR _RevPY = CALCULATE([$ Total Revenue (£)], FILTER(ALL(dim_season), dim_season[start_year] = _PrevStartYear))
			VAR _RevG = DIVIDE(_Rev - _RevPY, _RevPY)
			VAR _RevClass = IF(ISBLANK(_RevG) || _RevG >= 0, "pos", "neg")
			VAR _RevArrow = IF(ISBLANK(_RevG), "•", IF(_RevG >= 0, "↑", "↓"))
			VAR _RevFmt = IF(ABS(_Rev) >= 1000000000, "£" & FORMAT(DIVIDE(_Rev, 1000000000), "0.00") & "bn", "£" & FORMAT(DIVIDE(_Rev, 1000000), "#,##0.0") & "m")
			VAR _RevPYFmt = IF(ISBLANK(_RevPY), "—", IF(ABS(_RevPY) >= 1000000000, "£" & FORMAT(DIVIDE(_RevPY, 1000000000), "0.00") & "bn", "£" & FORMAT(DIVIDE(_RevPY, 1000000), "#,##0.0") & "m"))
			VAR _RevGFmt = IF(ISBLANK(_RevG), "—", FORMAT(ABS(_RevG), "0.0%"))
			
			VAR _Cost = [$ Total Cost (£)]
			VAR _CostPY = CALCULATE([$ Total Cost (£)], FILTER(ALL(dim_season), dim_season[start_year] = _PrevStartYear))
			VAR _CostG = DIVIDE(_Cost - _CostPY, _CostPY)
			VAR _CostClass = IF(ISBLANK(_CostG) || _CostG <= 0, "pos", "neg")
			VAR _CostArrow = IF(ISBLANK(_CostG), "•", IF(_CostG >= 0, "↑", "↓"))
			VAR _CostFmt = IF(ABS(_Cost) >= 1000000000, "£" & FORMAT(DIVIDE(_Cost, 1000000000), "0.00") & "bn", "£" & FORMAT(DIVIDE(_Cost, 1000000), "#,##0.0") & "m")
			VAR _CostPYFmt = IF(ISBLANK(_CostPY), "—", IF(ABS(_CostPY) >= 1000000000, "£" & FORMAT(DIVIDE(_CostPY, 1000000000), "0.00") & "bn", "£" & FORMAT(DIVIDE(_CostPY, 1000000), "#,##0.0") & "m"))
			VAR _CostGFmt = IF(ISBLANK(_CostG), "—", FORMAT(ABS(_CostG), "0.0%"))
			
			VAR _Net = [$ Net Profit/Loss (£)]
			VAR _NetPY = CALCULATE([$ Net Profit/Loss (£)], FILTER(ALL(dim_season), dim_season[start_year] = _PrevStartYear))
			VAR _NetG = DIVIDE(_Net - _NetPY, ABS(_NetPY))
			VAR _NetClass = IF(ISBLANK(_NetG) || _NetG >= 0, "pos", "neg")
			VAR _NetArrow = IF(ISBLANK(_NetG), "•", IF(_NetG >= 0, "↑", "↓"))
			VAR _NetFmt = IF(ABS(_Net) >= 1000000000, "£" & FORMAT(DIVIDE(_Net, 1000000000), "0.00") & "bn", "£" & FORMAT(DIVIDE(_Net, 1000000), "#,##0.0") & "m")
			VAR _NetPYFmt = IF(ISBLANK(_NetPY), "—", IF(ABS(_NetPY) >= 1000000000, "£" & FORMAT(DIVIDE(_NetPY, 1000000000), "0.00") & "bn", "£" & FORMAT(DIVIDE(_NetPY, 1000000), "#,##0.0") & "m"))
			VAR _NetGFmt = IF(ISBLANK(_NetG), "—", FORMAT(ABS(_NetG), "0.0%"))
			
			VAR _Wage = [% Wage to Revenue Ratio]
			VAR _WagePY = CALCULATE([% Wage to Revenue Ratio], FILTER(ALL(dim_season), dim_season[start_year] = _PrevStartYear))
			VAR _WageDelta = _Wage - _WagePY
			VAR _WageClass = IF(ISBLANK(_WageDelta) || _WageDelta <= 0, "pos", "neg")
			VAR _WageArrow = IF(ISBLANK(_WageDelta), "•", IF(_WageDelta >= 0, "↑", "↓"))
			VAR _WageFmt = FORMAT(_Wage, "0.0%")
			VAR _WagePYFmt = IF(ISBLANK(_WagePY), "—", FORMAT(_WagePY, "0.0%"))
			VAR _WageGFmt = IF(ISBLANK(_WageDelta), "—", FORMAT(ABS(_WageDelta) * 100, "0.0") & " pp")
			RETURN
			"<style>
			.cv{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;width:100%;height:100%;font-family:'Segoe UI',sans-serif;padding:6px;box-sizing:border-box;}
			.ci{background:#141E30;border-radius:8px;border:1px solid #2c3b54;border-left:3px solid #D4AF37;padding:11px 12px;display:flex;flex-direction:column;justify-content:space-between;min-width:0;overflow:hidden;}
			.cl{color:#D4AF37;font-size:9px;text-transform:uppercase;letter-spacing:1.2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
			.cn{color:#fff;font-size:20px;font-weight:700;line-height:1.05;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}
			.cf{display:flex;align-items:center;gap:7px;justify-content:flex-end;min-width:0;}
			.cp{font-size:10px;font-weight:700;padding:2px 7px;border-radius:99px;white-space:nowrap;}
			.pos{background:#052e16;border:1px solid #00A651;color:#4ade80;}
			.neg{background:#450a0a;border:1px solid #D62D20;color:#f87171;}
			.cy{font-size:10px;color:#7FA4CF;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
			</style>
			<div class=""cv"">
			  <div class=""ci""><div class=""cl"">Revenue</div><div class=""cn"">" & _RevFmt & "</div><div class=""cf""><span class=""cp " & _RevClass & """>" & _RevArrow & " " & _RevGFmt & "</span><span class=""cy"">vs PY: " & _RevPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Total Cost</div><div class=""cn"">" & _CostFmt & "</div><div class=""cf""><span class=""cp " & _CostClass & """>" & _CostArrow & " " & _CostGFmt & "</span><span class=""cy"">vs PY: " & _CostPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Net P/L</div><div class=""cn"">" & _NetFmt & "</div><div class=""cf""><span class=""cp " & _NetClass & """>" & _NetArrow & " " & _NetGFmt & "</span><span class=""cy"">vs PY: " & _NetPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Wage / Revenue</div><div class=""cn"">" & _WageFmt & "</div><div class=""cf""><span class=""cp " & _WageClass & """>" & _WageArrow & " " & _WageGFmt & "</span><span class=""cy"">vs PY: " & _WagePYFmt & "</span></div></div>
			</div>"
		displayFolder: 7_Visuals
		lineageTag: c1e0b2dd-3603-4892-92e5-838ce9fc5b31

	measure 'VIS HTML Transfer Snapshot' =
			
			VAR _CurrentStartYear = SELECTEDVALUE(dim_season[start_year])
			VAR _PrevStartYear = _CurrentStartYear - 1
			VAR _HasSingleSeason = NOT ISBLANK(_CurrentStartYear)
			
			VAR _Spend = [$ Total Transfer Spend (£)]
			VAR _SpendPY =
			    IF(
			        _HasSingleSeason,
			        CALCULATE(
			            [$ Total Transfer Spend (£)],
			            REMOVEFILTERS(dim_season),
			            dim_season[start_year] = _PrevStartYear
			        )
			    )
			VAR _SpendG = DIVIDE(_Spend - _SpendPY, ABS(_SpendPY))
			VAR _SpendClass = IF(ISBLANK(_SpendG) || _SpendG <= 0, "pos", "neg")
			VAR _SpendArrow = IF(ISBLANK(_SpendG), "•", IF(_SpendG >= 0, "↑", "↓"))
			VAR _SpendFmt = IF(ABS(_Spend) >= 1000000000, "£" & FORMAT(DIVIDE(_Spend, 1000000000), "0.00") & "bn", "£" & FORMAT(DIVIDE(_Spend, 1000000), "#,##0.0") & "m")
			VAR _SpendPYFmt = IF(ISBLANK(_SpendPY), "—", IF(ABS(_SpendPY) >= 1000000000, "£" & FORMAT(DIVIDE(_SpendPY, 1000000000), "0.00") & "bn", "£" & FORMAT(DIVIDE(_SpendPY, 1000000), "#,##0.0") & "m"))
			VAR _SpendGFmt = IF(ISBLANK(_SpendG), "—", FORMAT(ABS(_SpendG), "0.0%"))
			
			VAR _Income = [$ Total Transfer Income (£)]
			VAR _IncomePY =
			    IF(
			        _HasSingleSeason,
			        CALCULATE(
			            [$ Total Transfer Income (£)],
			            REMOVEFILTERS(dim_season),
			            dim_season[start_year] = _PrevStartYear
			        )
			    )
			VAR _IncomeG = DIVIDE(_Income - _IncomePY, ABS(_IncomePY))
			VAR _IncomeClass = IF(ISBLANK(_IncomeG) || _IncomeG >= 0, "pos", "neg")
			VAR _IncomeArrow = IF(ISBLANK(_IncomeG), "•", IF(_IncomeG >= 0, "↑", "↓"))
			VAR _IncomeFmt = IF(ABS(_Income) >= 1000000000, "£" & FORMAT(DIVIDE(_Income, 1000000000), "0.00") & "bn", "£" & FORMAT(DIVIDE(_Income, 1000000), "#,##0.0") & "m")
			VAR _IncomePYFmt = IF(ISBLANK(_IncomePY), "—", IF(ABS(_IncomePY) >= 1000000000, "£" & FORMAT(DIVIDE(_IncomePY, 1000000000), "0.00") & "bn", "£" & FORMAT(DIVIDE(_IncomePY, 1000000), "#,##0.0") & "m"))
			VAR _IncomeGFmt = IF(ISBLANK(_IncomeG), "—", FORMAT(ABS(_IncomeG), "0.0%"))
			
			VAR _Net = [$ Net Transfer Spend (£)]
			VAR _NetPY =
			    IF(
			        _HasSingleSeason,
			        CALCULATE(
			            [$ Net Transfer Spend (£)],
			            REMOVEFILTERS(dim_season),
			            dim_season[start_year] = _PrevStartYear
			        )
			    )
			VAR _NetG = DIVIDE(_Net - _NetPY, ABS(_NetPY))
			VAR _NetClass = IF(ISBLANK(_NetG) || _NetG <= 0, "pos", "neg")
			VAR _NetArrow = IF(ISBLANK(_NetG), "•", IF(_NetG >= 0, "↑", "↓"))
			VAR _NetFmt = IF(ABS(_Net) >= 1000000000, "£" & FORMAT(DIVIDE(_Net, 1000000000), "0.00") & "bn", "£" & FORMAT(DIVIDE(_Net, 1000000), "#,##0.0") & "m")
			VAR _NetPYFmt = IF(ISBLANK(_NetPY), "—", IF(ABS(_NetPY) >= 1000000000, "£" & FORMAT(DIVIDE(_NetPY, 1000000000), "0.00") & "bn", "£" & FORMAT(DIVIDE(_NetPY, 1000000), "#,##0.0") & "m"))
			VAR _NetGFmt = IF(ISBLANK(_NetG), "—", FORMAT(ABS(_NetG), "0.0%"))
			
			VAR _In = [# Total Transfers IN]
			VAR _InPY =
			    IF(
			        _HasSingleSeason,
			        CALCULATE(
			            [# Total Transfers IN],
			            REMOVEFILTERS(dim_season),
			            dim_season[start_year] = _PrevStartYear
			        )
			    )
			VAR _InG = DIVIDE(_In - _InPY, ABS(_InPY))
			VAR _InClass = IF(ISBLANK(_InG) || _InG >= 0, "pos", "neg")
			VAR _InArrow = IF(ISBLANK(_InG), "•", IF(_InG >= 0, "↑", "↓"))
			VAR _InFmt = FORMAT(_In, "#,##0")
			VAR _InPYFmt = IF(ISBLANK(_InPY), "—", FORMAT(_InPY, "#,##0"))
			VAR _InGFmt = IF(ISBLANK(_InG), "—", FORMAT(ABS(_InG), "0.0%"))
			
			VAR _Out = [# Total Transfers OUT]
			VAR _OutPY =
			    IF(
			        _HasSingleSeason,
			        CALCULATE(
			            [# Total Transfers OUT],
			            REMOVEFILTERS(dim_season),
			            dim_season[start_year] = _PrevStartYear
			        )
			    )
			VAR _OutG = DIVIDE(_Out - _OutPY, ABS(_OutPY))
			VAR _OutClass = IF(ISBLANK(_OutG) || _OutG >= 0, "pos", "neg")
			VAR _OutArrow = IF(ISBLANK(_OutG), "•", IF(_OutG >= 0, "↑", "↓"))
			VAR _OutFmt = FORMAT(_Out, "#,##0")
			VAR _OutPYFmt = IF(ISBLANK(_OutPY), "—", FORMAT(_OutPY, "#,##0"))
			VAR _OutGFmt = IF(ISBLANK(_OutG), "—", FORMAT(ABS(_OutG), "0.0%"))
			
			VAR _Flow = _In - _Out
			VAR _FlowFmt = IF(_Flow > 0, "+" & FORMAT(_Flow, "#,##0"), FORMAT(_Flow, "#,##0"))
			VAR _ActivityFmt = _InFmt & " / " & _OutFmt
			
			VAR _Ratio = [$ Value vs Fee Ratio]
			VAR _RatioPY =
			    IF(
			        _HasSingleSeason,
			        CALCULATE(
			            [$ Value vs Fee Ratio],
			            REMOVEFILTERS(dim_season),
			            dim_season[start_year] = _PrevStartYear
			        )
			    )
			VAR _RatioG = DIVIDE(_Ratio - _RatioPY, ABS(_RatioPY))
			VAR _RatioClass = IF(ISBLANK(_RatioG) || _RatioG >= 0, "pos", "neg")
			VAR _RatioArrow = IF(ISBLANK(_RatioG), "•", IF(_RatioG >= 0, "↑", "↓"))
			VAR _RatioFmt = FORMAT(_Ratio, "0.00") & "x"
			VAR _RatioPYFmt = IF(ISBLANK(_RatioPY), "—", FORMAT(_RatioPY, "0.00") & "x")
			VAR _RatioGFmt = IF(ISBLANK(_RatioG), "—", FORMAT(ABS(_RatioG), "0.0%"))
			RETURN
			"<style>
			.cv{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;width:100%;height:100%;font-family:'Segoe UI',sans-serif;padding:6px;box-sizing:border-box;}
			.ci{background:#141E30;border-radius:8px;border:1px solid #2c3b54;border-left:3px solid #D4AF37;padding:11px 12px;display:flex;flex-direction:column;justify-content:space-between;min-width:0;overflow:hidden;}
			.cl{color:#D4AF37;font-size:9px;text-transform:uppercase;letter-spacing:1.2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
			.cn{color:#fff;font-size:18px;font-weight:700;line-height:1.05;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}
			.cf{display:flex;align-items:center;gap:7px;justify-content:flex-end;min-width:0;}
			.cp{font-size:10px;font-weight:700;padding:2px 7px;border-radius:99px;white-space:nowrap;}
			.pos{background:#052e16;border:1px solid #00A651;color:#4ade80;}
			.neg{background:#450a0a;border:1px solid #D62D20;color:#f87171;}
			.neu{background:#172a43;border:1px solid #416f9f;color:#9cc5ee;}
			.cy{font-size:10px;color:#7FA4CF;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
			</style>
			<div class=""cv"">
			  <div class=""ci""><div class=""cl"">Transfer Spend</div><div class=""cn"">" & _SpendFmt & "</div><div class=""cf""><span class=""cp " & _SpendClass & """>" & _SpendArrow & " " & _SpendGFmt & "</span><span class=""cy"">vs PY: " & _SpendPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Transfer Income</div><div class=""cn"">" & _IncomeFmt & "</div><div class=""cf""><span class=""cp " & _IncomeClass & """>" & _IncomeArrow & " " & _IncomeGFmt & "</span><span class=""cy"">vs PY: " & _IncomePYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Net Spend</div><div class=""cn"">" & _NetFmt & "</div><div class=""cf""><span class=""cp " & _NetClass & """>" & _NetArrow & " " & _NetGFmt & "</span><span class=""cy"">vs PY: " & _NetPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Transfers IN / OUT</div><div class=""cn"">" & _ActivityFmt & "</div><div class=""cf""><span class=""cp neu"">Net " & _FlowFmt & "</span><span class=""cy"">in / out</span></div></div>
			  <div class=""ci""><div class=""cl"">Value / Fee</div><div class=""cn"">" & _RatioFmt & "</div><div class=""cf""><span class=""cp " & _RatioClass & """>" & _RatioArrow & " " & _RatioGFmt & "</span><span class=""cy"">vs PY: " & _RatioPYFmt & "</span></div></div>
			</div>"
		displayFolder: 7_Visuals
		lineageTag: 85e332a4-7496-4a28-ad12-5c1fd4281a9b

	measure 'VIS HTML Season Overview Snapshot' =
			
			VAR _CurrentStartYear = SELECTEDVALUE(dim_season[start_year])
			VAR _PrevStartYear = _CurrentStartYear - 1
			VAR _HasSingleSeason = NOT ISBLANK(_CurrentStartYear)
			
			VAR _PL = [REF PL Position]
			VAR _PLPY =
			    IF(
			        _HasSingleSeason,
			        CALCULATE([REF PL Position], REMOVEFILTERS(dim_season), dim_season[start_year] = _PrevStartYear)
			    )
			VAR _PLNum = IFERROR(VALUE(_PL), BLANK())
			VAR _PLPYNum = IFERROR(VALUE(_PLPY), BLANK())
			VAR _PLMove = _PLPYNum - _PLNum
			VAR _PLClass = IF(ISBLANK(_PLMove) || _PLMove >= 0, "pos", "neg")
			VAR _PLArrow = IF(ISBLANK(_PLMove), "•", IF(_PLMove >= 0, "↑", "↓"))
			VAR _PLMoveFmt = IF(ISBLANK(_PLMove), "—", FORMAT(ABS(_PLMove), "#,##0") & " places")
			VAR _PLPYFmt = IF(ISBLANK(_PLPY), "—", _PLPY)
			
			VAR _Points = [# PL Points]
			VAR _PointsPY =
			    IF(
			        _HasSingleSeason,
			        CALCULATE([# PL Points], REMOVEFILTERS(dim_season), dim_season[start_year] = _PrevStartYear)
			    )
			VAR _PointsG = DIVIDE(_Points - _PointsPY, _PointsPY)
			VAR _PointsClass = IF(ISBLANK(_PointsG) || _PointsG >= 0, "pos", "neg")
			VAR _PointsArrow = IF(ISBLANK(_PointsG), "•", IF(_PointsG >= 0, "↑", "↓"))
			VAR _PointsFmt = FORMAT(_Points, "#,##0")
			VAR _PointsPYFmt = IF(ISBLANK(_PointsPY), "—", FORMAT(_PointsPY, "#,##0"))
			VAR _PointsGFmt = IF(ISBLANK(_PointsG), "—", FORMAT(ABS(_PointsG), "0.0%"))
			
			VAR _Win = [% Win Rate]
			VAR _WinPY =
			    IF(
			        _HasSingleSeason,
			        CALCULATE([% Win Rate], REMOVEFILTERS(dim_season), dim_season[start_year] = _PrevStartYear)
			    )
			VAR _WinDelta = _Win - _WinPY
			VAR _WinClass = IF(ISBLANK(_WinDelta) || _WinDelta >= 0, "pos", "neg")
			VAR _WinArrow = IF(ISBLANK(_WinDelta), "•", IF(_WinDelta >= 0, "↑", "↓"))
			VAR _WinFmt = FORMAT(_Win, "0.0%")
			VAR _WinPYFmt = IF(ISBLANK(_WinPY), "—", FORMAT(_WinPY, "0.0%"))
			VAR _WinGFmt = IF(ISBLANK(_WinDelta), "—", FORMAT(ABS(_WinDelta) * 100, "0.0") & " pp")
			
			VAR _Trophies = [# Trophies Won]
			VAR _TrophiesPY =
			    IF(
			        _HasSingleSeason,
			        CALCULATE([# Trophies Won], REMOVEFILTERS(dim_season), dim_season[start_year] = _PrevStartYear)
			    )
			VAR _TrophiesDelta = _Trophies - _TrophiesPY
			VAR _TrophiesClass = IF(ISBLANK(_TrophiesDelta) || _TrophiesDelta >= 0, "pos", "neg")
			VAR _TrophiesArrow = IF(ISBLANK(_TrophiesDelta), "•", IF(_TrophiesDelta >= 0, "↑", "↓"))
			VAR _TrophiesFmt = FORMAT(_Trophies, "#,##0")
			VAR _TrophiesPYFmt = IF(ISBLANK(_TrophiesPY), "—", FORMAT(_TrophiesPY, "#,##0"))
			VAR _TrophiesGFmt = IF(ISBLANK(_TrophiesDelta), "—", FORMAT(ABS(_TrophiesDelta), "#,##0"))
			
			VAR _Net = [$ Net Profit/Loss (£)]
			VAR _NetPY =
			    IF(
			        _HasSingleSeason,
			        CALCULATE([$ Net Profit/Loss (£)], REMOVEFILTERS(dim_season), dim_season[start_year] = _PrevStartYear)
			    )
			VAR _NetG = DIVIDE(_Net - _NetPY, ABS(_NetPY))
			VAR _NetClass = IF(ISBLANK(_NetG) || _NetG >= 0, "pos", "neg")
			VAR _NetArrow = IF(ISBLANK(_NetG), "•", IF(_NetG >= 0, "↑", "↓"))
			VAR _NetFmt = IF(ABS(_Net) >= 1000000000, "£" & FORMAT(DIVIDE(_Net, 1000000000), "0.00") & "bn", "£" & FORMAT(DIVIDE(_Net, 1000000), "#,##0.0") & "m")
			VAR _NetPYFmt = IF(ISBLANK(_NetPY), "—", IF(ABS(_NetPY) >= 1000000000, "£" & FORMAT(DIVIDE(_NetPY, 1000000000), "0.00") & "bn", "£" & FORMAT(DIVIDE(_NetPY, 1000000), "#,##0.0") & "m"))
			VAR _NetGFmt = IF(ISBLANK(_NetG), "—", FORMAT(ABS(_NetG), "0.0%"))
			RETURN
			"<style>
			.cv{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;width:100%;height:100%;font-family:'Segoe UI',sans-serif;padding:6px;box-sizing:border-box;}
			.ci{background:#141E30;border-radius:8px;border:1px solid #2c3b54;border-left:3px solid #D4AF37;padding:11px 12px;display:flex;flex-direction:column;justify-content:space-between;min-width:0;overflow:hidden;}
			.cl{color:#D4AF37;font-size:9px;text-transform:uppercase;letter-spacing:1.2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
			.cn{color:#fff;font-size:18px;font-weight:700;line-height:1.05;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}
			.cf{display:flex;align-items:center;gap:7px;justify-content:flex-end;min-width:0;}
			.cp{font-size:10px;font-weight:700;padding:2px 7px;border-radius:99px;white-space:nowrap;}
			.pos{background:#052e16;border:1px solid #00A651;color:#4ade80;}
			.neg{background:#450a0a;border:1px solid #D62D20;color:#f87171;}
			.cy{font-size:10px;color:#7FA4CF;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
			</style>
			<div class=""cv"">
			  <div class=""ci""><div class=""cl"">PL Finish</div><div class=""cn"">" & _PL & "</div><div class=""cf""><span class=""cp " & _PLClass & """>" & _PLArrow & " " & _PLMoveFmt & "</span><span class=""cy"">vs PY: " & _PLPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">PL Points</div><div class=""cn"">" & _PointsFmt & "</div><div class=""cf""><span class=""cp " & _PointsClass & """>" & _PointsArrow & " " & _PointsGFmt & "</span><span class=""cy"">vs PY: " & _PointsPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Win Rate</div><div class=""cn"">" & _WinFmt & "</div><div class=""cf""><span class=""cp " & _WinClass & """>" & _WinArrow & " " & _WinGFmt & "</span><span class=""cy"">vs PY: " & _WinPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Trophies</div><div class=""cn"">" & _TrophiesFmt & "</div><div class=""cf""><span class=""cp " & _TrophiesClass & """>" & _TrophiesArrow & " " & _TrophiesGFmt & "</span><span class=""cy"">vs PY: " & _TrophiesPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Net P/L</div><div class=""cn"">" & _NetFmt & "</div><div class=""cf""><span class=""cp " & _NetClass & """>" & _NetArrow & " " & _NetGFmt & "</span><span class=""cy"">vs PY: " & _NetPYFmt & "</span></div></div>
			</div>"
		displayFolder: 7_Visuals
		lineageTag: 72588439-0044-4400-8556-dc4030a1c602

	measure 'VIS HTML Wage Snapshot' =
			
			VAR _CurrentStartYear = SELECTEDVALUE(dim_season[start_year])
			VAR _PrevStartYear = _CurrentStartYear - 1
			VAR _HasSingleSeason = NOT ISBLANK(_CurrentStartYear)
			
			VAR _Annual = [$ Total Annual Wage Bill (£)]
			VAR _AnnualPY = IF(_HasSingleSeason, CALCULATE([$ Total Annual Wage Bill (£)], REMOVEFILTERS(dim_season), dim_season[start_year] = _PrevStartYear))
			VAR _AnnualG = DIVIDE(_Annual - _AnnualPY, ABS(_AnnualPY))
			VAR _AnnualClass = IF(ISBLANK(_AnnualG) || _AnnualG <= 0, "pos", "neg")
			VAR _AnnualArrow = IF(ISBLANK(_AnnualG), "•", IF(_AnnualG >= 0, "↑", "↓"))
			VAR _AnnualFmt = IF(ABS(_Annual) >= 1000000000, "£" & FORMAT(DIVIDE(_Annual, 1000000000), "0.00") & "bn", "£" & FORMAT(DIVIDE(_Annual, 1000000), "#,##0.0") & "m")
			VAR _AnnualPYFmt = IF(ISBLANK(_AnnualPY), "—", IF(ABS(_AnnualPY) >= 1000000000, "£" & FORMAT(DIVIDE(_AnnualPY, 1000000000), "0.00") & "bn", "£" & FORMAT(DIVIDE(_AnnualPY, 1000000), "#,##0.0") & "m"))
			VAR _AnnualGFmt = IF(ISBLANK(_AnnualG), "—", FORMAT(ABS(_AnnualG), "0.0%"))
			
			VAR _Weekly = [$ Avg Weekly Wage Bill (£)]
			VAR _WeeklyPY = IF(_HasSingleSeason, CALCULATE([$ Avg Weekly Wage Bill (£)], REMOVEFILTERS(dim_season), dim_season[start_year] = _PrevStartYear))
			VAR _WeeklyG = DIVIDE(_Weekly - _WeeklyPY, ABS(_WeeklyPY))
			VAR _WeeklyClass = IF(ISBLANK(_WeeklyG) || _WeeklyG <= 0, "pos", "neg")
			VAR _WeeklyArrow = IF(ISBLANK(_WeeklyG), "•", IF(_WeeklyG >= 0, "↑", "↓"))
			VAR _WeeklyFmt = "£" & FORMAT(DIVIDE(_Weekly, 1000), "#,##0.0") & "k"
			VAR _WeeklyPYFmt = IF(ISBLANK(_WeeklyPY), "—", "£" & FORMAT(DIVIDE(_WeeklyPY, 1000), "#,##0.0") & "k")
			VAR _WeeklyGFmt = IF(ISBLANK(_WeeklyG), "—", FORMAT(ABS(_WeeklyG), "0.0%"))
			
			VAR _Ratio = [% Wage to Revenue Ratio]
			VAR _RatioPY = IF(_HasSingleSeason, CALCULATE([% Wage to Revenue Ratio], REMOVEFILTERS(dim_season), dim_season[start_year] = _PrevStartYear))
			VAR _RatioDelta = _Ratio - _RatioPY
			VAR _RatioClass = IF(ISBLANK(_RatioDelta) || _RatioDelta <= 0, "pos", "neg")
			VAR _RatioArrow = IF(ISBLANK(_RatioDelta), "•", IF(_RatioDelta >= 0, "↑", "↓"))
			VAR _RatioFmt = FORMAT(_Ratio, "0.0%")
			VAR _RatioPYFmt = IF(ISBLANK(_RatioPY), "—", FORMAT(_RatioPY, "0.0%"))
			VAR _RatioGFmt = IF(ISBLANK(_RatioDelta), "—", FORMAT(ABS(_RatioDelta) * 100, "0.0") & " pp")
			
			VAR _PerApp = [$ Wage per Appearance (£)]
			VAR _PerAppPY = IF(_HasSingleSeason, CALCULATE([$ Wage per Appearance (£)], REMOVEFILTERS(dim_season), dim_season[start_year] = _PrevStartYear))
			VAR _PerAppG = DIVIDE(_PerApp - _PerAppPY, ABS(_PerAppPY))
			VAR _PerAppClass = IF(ISBLANK(_PerAppG) || _PerAppG <= 0, "pos", "neg")
			VAR _PerAppArrow = IF(ISBLANK(_PerAppG), "•", IF(_PerAppG >= 0, "↑", "↓"))
			VAR _PerAppFmt = "£" & FORMAT(DIVIDE(_PerApp, 1000), "#,##0.0") & "k"
			VAR _PerAppPYFmt = IF(ISBLANK(_PerAppPY), "—", "£" & FORMAT(DIVIDE(_PerAppPY, 1000), "#,##0.0") & "k")
			VAR _PerAppGFmt = IF(ISBLANK(_PerAppG), "—", FORMAT(ABS(_PerAppG), "0.0%"))
			
			VAR _Highest = IF(ISBLANK([$ Highest Paid Player (£)]), "—", [$ Highest Paid Player (£)])
			RETURN
			"<style>
			.cv{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;width:100%;height:100%;font-family:'Segoe UI',sans-serif;padding:6px;box-sizing:border-box;}
			.ci{background:#141E30;border-radius:8px;border:1px solid #2c3b54;border-left:3px solid #D4AF37;padding:11px 12px;display:flex;flex-direction:column;justify-content:space-between;min-width:0;overflow:hidden;}
			.cl{color:#D4AF37;font-size:9px;text-transform:uppercase;letter-spacing:1.2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
			.cn{color:#fff;font-size:18px;font-weight:700;line-height:1.05;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}
			.cf{display:flex;align-items:center;gap:7px;justify-content:flex-end;min-width:0;}
			.cp{font-size:10px;font-weight:700;padding:2px 7px;border-radius:99px;white-space:nowrap;}
			.pos{background:#052e16;border:1px solid #00A651;color:#4ade80;}
			.neg{background:#450a0a;border:1px solid #D62D20;color:#f87171;}
			.neu{background:#172a43;border:1px solid #416f9f;color:#9cc5ee;}
			.cy{font-size:10px;color:#7FA4CF;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
			</style>
			<div class=""cv"">
			  <div class=""ci""><div class=""cl"">Annual Wage Bill</div><div class=""cn"">" & _AnnualFmt & "</div><div class=""cf""><span class=""cp " & _AnnualClass & """>" & _AnnualArrow & " " & _AnnualGFmt & "</span><span class=""cy"">vs PY: " & _AnnualPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Avg Weekly Wage</div><div class=""cn"">" & _WeeklyFmt & "</div><div class=""cf""><span class=""cp " & _WeeklyClass & """>" & _WeeklyArrow & " " & _WeeklyGFmt & "</span><span class=""cy"">vs PY: " & _WeeklyPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Wage / Revenue</div><div class=""cn"">" & _RatioFmt & "</div><div class=""cf""><span class=""cp " & _RatioClass & """>" & _RatioArrow & " " & _RatioGFmt & "</span><span class=""cy"">vs PY: " & _RatioPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Wage / Appearance</div><div class=""cn"">" & _PerAppFmt & "</div><div class=""cf""><span class=""cp " & _PerAppClass & """>" & _PerAppArrow & " " & _PerAppGFmt & "</span><span class=""cy"">vs PY: " & _PerAppPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Highest Paid</div><div class=""cn"">" & _Highest & "</div><div class=""cf""><span class=""cp neu"">player</span><span class=""cy"">current selection</span></div></div>
			</div>"
		displayFolder: 7_Visuals
		lineageTag: 8a7bfdb0-e0cc-4d5c-86e2-2c4438ebd8bc

	measure 'VIS HTML Player Performance Snapshot' =
			
			VAR _CurrentStartYear = SELECTEDVALUE(dim_season[start_year])
			VAR _PrevStartYear = _CurrentStartYear - 1
			VAR _HasSingleSeason = NOT ISBLANK(_CurrentStartYear)
			
			VAR _Goals = [# Total Goals]
			VAR _GoalsPY = IF(_HasSingleSeason, CALCULATE([# Total Goals], REMOVEFILTERS(dim_season), dim_season[start_year] = _PrevStartYear))
			VAR _GoalsG = DIVIDE(_Goals - _GoalsPY, ABS(_GoalsPY))
			VAR _GoalsClass = IF(ISBLANK(_GoalsG) || _GoalsG >= 0, "pos", "neg")
			VAR _GoalsArrow = IF(ISBLANK(_GoalsG), "•", IF(_GoalsG >= 0, "↑", "↓"))
			VAR _GoalsFmt = FORMAT(_Goals, "#,##0")
			VAR _GoalsPYFmt = IF(ISBLANK(_GoalsPY), "—", FORMAT(_GoalsPY, "#,##0"))
			VAR _GoalsGFmt = IF(ISBLANK(_GoalsG), "—", FORMAT(ABS(_GoalsG), "0.0%"))
			
			VAR _Assists = [# Total Assists]
			VAR _AssistsPY = IF(_HasSingleSeason, CALCULATE([# Total Assists], REMOVEFILTERS(dim_season), dim_season[start_year] = _PrevStartYear))
			VAR _AssistsG = DIVIDE(_Assists - _AssistsPY, ABS(_AssistsPY))
			VAR _AssistsClass = IF(ISBLANK(_AssistsG) || _AssistsG >= 0, "pos", "neg")
			VAR _AssistsArrow = IF(ISBLANK(_AssistsG), "•", IF(_AssistsG >= 0, "↑", "↓"))
			VAR _AssistsFmt = FORMAT(_Assists, "#,##0")
			VAR _AssistsPYFmt = IF(ISBLANK(_AssistsPY), "—", FORMAT(_AssistsPY, "#,##0"))
			VAR _AssistsGFmt = IF(ISBLANK(_AssistsG), "—", FORMAT(ABS(_AssistsG), "0.0%"))
			
			VAR _GC = [# Total Goal Contributions]
			VAR _GCPY = IF(_HasSingleSeason, CALCULATE([# Total Goal Contributions], REMOVEFILTERS(dim_season), dim_season[start_year] = _PrevStartYear))
			VAR _GCG = DIVIDE(_GC - _GCPY, ABS(_GCPY))
			VAR _GCClass = IF(ISBLANK(_GCG) || _GCG >= 0, "pos", "neg")
			VAR _GCArrow = IF(ISBLANK(_GCG), "•", IF(_GCG >= 0, "↑", "↓"))
			VAR _GCFmt = FORMAT(_GC, "#,##0")
			VAR _GCPYFmt = IF(ISBLANK(_GCPY), "—", FORMAT(_GCPY, "#,##0"))
			VAR _GCGFmt = IF(ISBLANK(_GCG), "—", FORMAT(ABS(_GCG), "0.0%"))
			
			VAR _Rating = [# Avg Player Rating]
			VAR _RatingPY = IF(_HasSingleSeason, CALCULATE([# Avg Player Rating], REMOVEFILTERS(dim_season), dim_season[start_year] = _PrevStartYear))
			VAR _RatingDelta = _Rating - _RatingPY
			VAR _RatingClass = IF(ISBLANK(_RatingDelta) || _RatingDelta >= 0, "pos", "neg")
			VAR _RatingArrow = IF(ISBLANK(_RatingDelta), "•", IF(_RatingDelta >= 0, "↑", "↓"))
			VAR _RatingFmt = FORMAT(_Rating, "0.00")
			VAR _RatingPYFmt = IF(ISBLANK(_RatingPY), "—", FORMAT(_RatingPY, "0.00"))
			VAR _RatingGFmt = IF(ISBLANK(_RatingDelta), "—", FORMAT(ABS(_RatingDelta), "0.00"))
			VAR _Apps = [# Total Appearances]
			VAR _AppsPY = IF(_HasSingleSeason, CALCULATE([# Total Appearances], REMOVEFILTERS(dim_season), dim_season[start_year] = _PrevStartYear))
			VAR _AppsFmt = FORMAT(_Apps, "#,##0")
			VAR _AppsPYFmt = IF(ISBLANK(_AppsPY), "—", FORMAT(_AppsPY, "#,##0"))
			
			VAR _Pass = [% Avg Pass Accuracy]
			VAR _PassPY = IF(_HasSingleSeason, CALCULATE([% Avg Pass Accuracy], REMOVEFILTERS(dim_season), dim_season[start_year] = _PrevStartYear))
			VAR _PassRate = DIVIDE(_Pass, IF(_Pass > 1, 100, 1))
			VAR _PassPYRate = DIVIDE(_PassPY, IF(_PassPY > 1, 100, 1))
			VAR _PassDelta = _PassRate - _PassPYRate
			VAR _PassClass = IF(ISBLANK(_PassDelta) || _PassDelta >= 0, "pos", "neg")
			VAR _PassArrow = IF(ISBLANK(_PassDelta), "•", IF(_PassDelta >= 0, "↑", "↓"))
			VAR _PassFmt = FORMAT(_PassRate, "0.0%")
			VAR _PassPYFmt = IF(ISBLANK(_PassPY), "—", FORMAT(_PassPYRate, "0.0%"))
			VAR _PassGFmt = IF(ISBLANK(_PassDelta), "—", FORMAT(ABS(_PassDelta) * 100, "0.0") & " pp")
			RETURN
			"<style>
			.cv{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;width:100%;height:100%;font-family:'Segoe UI',sans-serif;padding:6px;box-sizing:border-box;}
			.ci{background:#141E30;border-radius:8px;border:1px solid #2c3b54;border-left:3px solid #D4AF37;padding:11px 12px;display:flex;flex-direction:column;justify-content:space-between;min-width:0;overflow:hidden;}
			.cl{color:#D4AF37;font-size:9px;text-transform:uppercase;letter-spacing:1.2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
			.cn{color:#fff;font-size:18px;font-weight:700;line-height:1.05;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}
			.cs{color:#7FA4CF;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
			.cf{display:flex;align-items:center;gap:7px;justify-content:flex-end;min-width:0;}
			.cp{font-size:10px;font-weight:700;padding:2px 7px;border-radius:99px;white-space:nowrap;}
			.pos{background:#052e16;border:1px solid #00A651;color:#4ade80;}
			.neg{background:#450a0a;border:1px solid #D62D20;color:#f87171;}
			.cy{font-size:10px;color:#7FA4CF;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
			</style>
			<div class=""cv"">
			  <div class=""ci""><div class=""cl"">Goals</div><div class=""cn"">" & _GoalsFmt & "</div><div class=""cf""><span class=""cp " & _GoalsClass & """>" & _GoalsArrow & " " & _GoalsGFmt & "</span><span class=""cy"">vs PY: " & _GoalsPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Assists</div><div class=""cn"">" & _AssistsFmt & "</div><div class=""cf""><span class=""cp " & _AssistsClass & """>" & _AssistsArrow & " " & _AssistsGFmt & "</span><span class=""cy"">vs PY: " & _AssistsPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Goal Contributions</div><div class=""cn"">" & _GCFmt & "</div><div class=""cf""><span class=""cp " & _GCClass & """>" & _GCArrow & " " & _GCGFmt & "</span><span class=""cy"">vs PY: " & _GCPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Avg Rating</div><div class=""cn"">" & _RatingFmt & "</div><div class=""cs"">Apps: " & _AppsFmt & " · vs PY: " & _AppsPYFmt & "</div><div class=""cf""><span class=""cp " & _RatingClass & """>" & _RatingArrow & " " & _RatingGFmt & "</span><span class=""cy"">vs PY: " & _RatingPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Pass Accuracy</div><div class=""cn"">" & _PassFmt & "</div><div class=""cf""><span class=""cp " & _PassClass & """>" & _PassArrow & " " & _PassGFmt & "</span><span class=""cy"">vs PY: " & _PassPYFmt & "</span></div></div>
			</div>"
		displayFolder: 7_Visuals
		lineageTag: 6665cffa-e017-434f-88bf-f63b28f8b381

	measure 'VIS HTML Chelsea Top Highlights' =
			
			VAR _Season = IF(ISBLANK([REF Current Season]), "—", [REF Current Season])
			VAR _TopScorer = IF(ISBLANK([REF Top Scorer Name]), "—", [REF Top Scorer Name] & " (" & FORMAT([# Top Scorer Goals], "#,##0") & " goals)")
			VAR _MVP = IF(ISBLANK([$ Most Valuable Player (£)]), "—", [$ Most Valuable Player (£)])
			VAR _Paid = IF(ISBLANK([$ Highest Paid Player (£)]), "—", [$ Highest Paid Player (£)])
			RETURN
			"<style>
			.hi{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;width:100%;height:100%;font-family:'Segoe UI',sans-serif;padding:6px;box-sizing:border-box;}
			.hc{background:#141E30;border-radius:8px;border:1px solid #2c3b54;border-left:3px solid #D4AF37;padding:14px 12px;display:flex;flex-direction:column;justify-content:center;overflow:hidden;min-width:0;}
			.hl{color:#D4AF37;font-size:9px;text-transform:uppercase;letter-spacing:1.4px;margin-bottom:6px;white-space:nowrap;}
			.hv{color:#fff;font-size:13px;font-weight:700;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}
			.hb{color:#7FA4CF;}
			</style>
			<div class=""hi"">
			  <div class=""hc""><div class=""hl"">Season</div><div class=""hv"">" & _Season & "</div></div>
			  <div class=""hc""><div class=""hl"">Top Scorer</div><div class=""hv"">" & _TopScorer & "</div></div>
			  <div class=""hc""><div class=""hl"">Most Valuable</div><div class=""hv hb"">" & _MVP & "</div></div>
			  <div class=""hc""><div class=""hl"">Highest Paid</div><div class=""hv"">" & _Paid & "</div></div>
			</div>"
		displayFolder: 7_Visuals
		lineageTag: 24b5d44d-9804-418e-86f3-7ddad36bef5e

	measure 'VIS HTML Squad Value Snapshot' =
			
			VAR _PrevStartYear = CALCULATE(MIN(dim_season[start_year]), ALLSELECTED(dim_season)) - 1
			
			VAR _Squad = [$ Squad Market Value (£)]
			VAR _SquadPY = CALCULATE([$ Squad Market Value (£)], FILTER(ALL(dim_season), dim_season[start_year] = _PrevStartYear))
			VAR _SquadG = DIVIDE(_Squad - _SquadPY, _SquadPY)
			VAR _SquadClass = IF(ISBLANK(_SquadG) || _SquadG >= 0, "pos", "neg")
			VAR _SquadArrow = IF(ISBLANK(_SquadG), "•", IF(_SquadG >= 0, "↑", "↓"))
			VAR _SquadFmt = IF(ABS(_Squad) >= 1000000000, "£" & FORMAT(DIVIDE(_Squad, 1000000000), "0.00") & "bn", "£" & FORMAT(DIVIDE(_Squad, 1000000), "#,##0.0") & "m")
			VAR _SquadPYFmt = IF(ISBLANK(_SquadPY), "—", IF(ABS(_SquadPY) >= 1000000000, "£" & FORMAT(DIVIDE(_SquadPY, 1000000000), "0.00") & "bn", "£" & FORMAT(DIVIDE(_SquadPY, 1000000), "#,##0.0") & "m"))
			VAR _SquadGFmt = IF(ISBLANK(_SquadG), "—", FORMAT(ABS(_SquadG), "0.0%"))
			
			VAR _Avg = [$ Avg Player Market Value (£)]
			VAR _AvgPY = CALCULATE([$ Avg Player Market Value (£)], FILTER(ALL(dim_season), dim_season[start_year] = _PrevStartYear))
			VAR _AvgG = DIVIDE(_Avg - _AvgPY, _AvgPY)
			VAR _AvgClass = IF(ISBLANK(_AvgG) || _AvgG >= 0, "pos", "neg")
			VAR _AvgArrow = IF(ISBLANK(_AvgG), "•", IF(_AvgG >= 0, "↑", "↓"))
			VAR _AvgFmt = "£" & FORMAT(DIVIDE(_Avg, 1000000), "#,##0.0") & "m"
			VAR _AvgPYFmt = IF(ISBLANK(_AvgPY), "—", "£" & FORMAT(DIVIDE(_AvgPY, 1000000), "#,##0.0") & "m")
			VAR _AvgGFmt = IF(ISBLANK(_AvgG), "—", FORMAT(ABS(_AvgG), "0.0%"))
			
			VAR _High = [$ Highest Player Market Value (£)]
			VAR _HighPY = CALCULATE([$ Highest Player Market Value (£)], FILTER(ALL(dim_season), dim_season[start_year] = _PrevStartYear))
			VAR _HighG = DIVIDE(_High - _HighPY, _HighPY)
			VAR _HighClass = IF(ISBLANK(_HighG) || _HighG >= 0, "pos", "neg")
			VAR _HighArrow = IF(ISBLANK(_HighG), "•", IF(_HighG >= 0, "↑", "↓"))
			VAR _HighFmt = "£" & FORMAT(DIVIDE(_High, 1000000), "#,##0.0") & "m"
			VAR _HighPYFmt = IF(ISBLANK(_HighPY), "—", "£" & FORMAT(DIVIDE(_HighPY, 1000000), "#,##0.0") & "m")
			VAR _HighGFmt = IF(ISBLANK(_HighG), "—", FORMAT(ABS(_HighG), "0.0%"))
			
			VAR _Players = [# Players in Latest Valuation Snapshot]
			VAR _PlayersPY = CALCULATE([# Players in Latest Valuation Snapshot], FILTER(ALL(dim_season), dim_season[start_year] = _PrevStartYear))
			VAR _PlayersG = DIVIDE(_Players - _PlayersPY, _PlayersPY)
			VAR _PlayersClass = IF(ISBLANK(_PlayersG) || _PlayersG >= 0, "pos", "neg")
			VAR _PlayersArrow = IF(ISBLANK(_PlayersG), "•", IF(_PlayersG >= 0, "↑", "↓"))
			VAR _PlayersFmt = FORMAT(_Players, "#,##0")
			VAR _PlayersPYFmt = IF(ISBLANK(_PlayersPY), "—", FORMAT(_PlayersPY, "#,##0"))
			VAR _PlayersGFmt = IF(ISBLANK(_PlayersG), "—", FORMAT(ABS(_PlayersG), "0.0%"))
			RETURN
			"<style>
			.cv{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;width:100%;height:100%;font-family:'Segoe UI',sans-serif;padding:6px;box-sizing:border-box;}
			.ci{background:#141E30;border-radius:8px;border:1px solid #2c3b54;border-left:3px solid #D4AF37;padding:11px 12px;display:flex;flex-direction:column;justify-content:space-between;min-width:0;overflow:hidden;}
			.cl{color:#D4AF37;font-size:9px;text-transform:uppercase;letter-spacing:1.2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
			.cn{color:#fff;font-size:20px;font-weight:700;line-height:1.05;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}
			.cf{display:flex;align-items:center;gap:7px;justify-content:flex-end;min-width:0;}
			.cp{font-size:10px;font-weight:700;padding:2px 7px;border-radius:99px;white-space:nowrap;}
			.pos{background:#052e16;border:1px solid #00A651;color:#4ade80;}
			.neg{background:#450a0a;border:1px solid #D62D20;color:#f87171;}
			.cy{font-size:10px;color:#7FA4CF;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
			</style>
			<div class=""cv"">
			  <div class=""ci""><div class=""cl"">Squad Value</div><div class=""cn"">" & _SquadFmt & "</div><div class=""cf""><span class=""cp " & _SquadClass & """>" & _SquadArrow & " " & _SquadGFmt & "</span><span class=""cy"">vs PY: " & _SquadPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Avg Player Value</div><div class=""cn"">" & _AvgFmt & "</div><div class=""cf""><span class=""cp " & _AvgClass & """>" & _AvgArrow & " " & _AvgGFmt & "</span><span class=""cy"">vs PY: " & _AvgPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Highest Value</div><div class=""cn"">" & _HighFmt & "</div><div class=""cf""><span class=""cp " & _HighClass & """>" & _HighArrow & " " & _HighGFmt & "</span><span class=""cy"">vs PY: " & _HighPYFmt & "</span></div></div>
			  <div class=""ci""><div class=""cl"">Players Snapshot</div><div class=""cn"">" & _PlayersFmt & "</div><div class=""cf""><span class=""cp " & _PlayersClass & """>" & _PlayersArrow & " " & _PlayersGFmt & "</span><span class=""cy"">vs PY: " & _PlayersPYFmt & "</span></div></div>
			</div>"
		displayFolder: 7_Visuals
		lineageTag: abbf52ca-11fa-43ec-beb3-f15d7194714e

	measure '$ Financial Impact (£)' =
			
			SUMX(
			    fact_financials,
			    IF(
			        fact_financials[type] = "Cost",
			        -fact_financials[amount_gbp],
			        fact_financials[amount_gbp]
			    )
			)
		formatString: 0
		displayFolder: 2_Financials\$\£
		lineageTag: df1f0009-e21a-4601-a059-a6bb653e29c6

	measure '$ Financial Impact (€)' =
			
			SUMX(
			    fact_financials,
			    IF(
			        fact_financials[type] = "Cost",
			        -fact_financials[amount_eur],
			        fact_financials[amount_eur]
			    )
			)
		formatString: 0
		displayFolder: 2_Financials\$\€
		lineageTag: 938fc566-48c4-4b73-9731-57550fa0d154

	measure 'VIS HTML Financial Sankey' =
			
			VAR _Revenue =
			    CALCULATE(SUM(fact_financials[amount_gbp]), fact_financials[type] = "Revenue")
			VAR _Cost =
			    CALCULATE(SUM(fact_financials[amount_gbp]), fact_financials[type] = "Cost")
			VAR _Broadcast =
			    CALCULATE(SUM(fact_financials[amount_gbp]), fact_financials[subcategory] = "Broadcast")
			VAR _Commercial =
			    CALCULATE(SUM(fact_financials[amount_gbp]), fact_financials[subcategory] = "Commercial")
			VAR _Matchday =
			    CALCULATE(SUM(fact_financials[amount_gbp]), fact_financials[subcategory] = "Matchday")
			VAR _PlayerSales =
			    CALCULATE(SUM(fact_financials[amount_gbp]), fact_financials[subcategory] = "Player Sales")
			VAR _Competition =
			    CALCULATE(SUM(fact_financials[amount_gbp]), fact_financials[subcategory] = "Competition Prize Money")
			VAR _Retail =
			    CALCULATE(SUM(fact_financials[amount_gbp]), fact_financials[subcategory] = "Retail and Merchandising")
			VAR _Hospitality =
			    CALCULATE(SUM(fact_financials[amount_gbp]), fact_financials[subcategory] = "Stadium Events and Hospitality")
			VAR _Friendly =
			    CALCULATE(SUM(fact_financials[amount_gbp]), fact_financials[subcategory] = "Friendly Matches")
			VAR _OtherIncome = _Retail + _Hospitality + _Friendly
			
			VAR _WagesPlayers =
			    CALCULATE(SUM(fact_financials[amount_gbp]), fact_financials[subcategory] = "Wages - Players")
			VAR _Amortisation =
			    CALCULATE(SUM(fact_financials[amount_gbp]), fact_financials[subcategory] = "Transfer Amortisation")
			VAR _AgentFees =
			    CALCULATE(SUM(fact_financials[amount_gbp]), fact_financials[subcategory] = "Agent Fees")
			VAR _WagesStaff =
			    CALCULATE(SUM(fact_financials[amount_gbp]), fact_financials[subcategory] = "Wages - Staff")
			VAR _Operations =
			    CALCULATE(SUM(fact_financials[amount_gbp]), fact_financials[subcategory] = "Operations")
			VAR _Academy =
			    CALCULATE(SUM(fact_financials[amount_gbp]), fact_financials[subcategory] = "Academy")
			VAR _Marketing =
			    CALCULATE(SUM(fact_financials[amount_gbp]), fact_financials[subcategory] = "Marketing")
			
			VAR _DirectCosts = _WagesPlayers + _Amortisation + _AgentFees
			VAR _OperatingCosts = _WagesStaff + _Operations + _Academy + _Marketing
			VAR _GrossProfit = _Revenue - _DirectCosts
			VAR _OperatingBalance = _GrossProfit - _OperatingCosts
			
			VAR _MaxValue =
			    MAXX(
			        {
			            _Revenue,
			            _Cost,
			            _Broadcast,
			            _Commercial,
			            _Matchday,
			            _PlayerSales,
			            _Competition,
			            _OtherIncome,
			            _DirectCosts,
			            _OperatingCosts,
			            ABS(_GrossProfit),
			            ABS(_OperatingBalance)
			        },
			        [Value]
			    )
			VAR _Scale = DIVIDE(82, _MaxValue, 0)
			
			VAR _BroadcastW = MAX(6, _Broadcast * _Scale)
			VAR _CommercialW = MAX(6, _Commercial * _Scale)
			VAR _MatchdayW = MAX(5, _Matchday * _Scale)
			VAR _PlayerSalesW = MAX(5, _PlayerSales * _Scale)
			VAR _CompetitionW = MAX(5, _Competition * _Scale)
			VAR _OtherIncomeW = MAX(4, _OtherIncome * _Scale)
			VAR _DirectW = MAX(8, _DirectCosts * _Scale)
			VAR _OperatingW = MAX(7, _OperatingCosts * _Scale)
			VAR _GrossW = MAX(7, ABS(_GrossProfit) * _Scale)
			VAR _BalanceW = MAX(6, ABS(_OperatingBalance) * _Scale)
			
			VAR _Green = "#59A472"
			VAR _Yellow = "#C8A84B"
			VAR _Red = "#E63535"
			VAR _GrossColor = IF(_GrossProfit >= 0, _Green, _Red)
			VAR _BalanceColor = IF(_OperatingBalance >= 0, _Green, _Red)
			VAR _BalanceLabel = IF(_OperatingBalance >= 0, "Net Profit", "Net Loss")
			
			VAR _FmtRevenue = "£" & FORMAT(DIVIDE(_Revenue, 1000000), "#,##0") & "m"
			VAR _FmtDirect = "£" & FORMAT(DIVIDE(_DirectCosts, 1000000), "#,##0") & "m"
			VAR _FmtOperating = "£" & FORMAT(DIVIDE(_OperatingCosts, 1000000), "#,##0") & "m"
			VAR _FmtGross = "£" & FORMAT(DIVIDE(_GrossProfit, 1000000), "#,##0") & "m"
			VAR _FmtBalance = "£" & FORMAT(DIVIDE(_OperatingBalance, 1000000), "#,##0") & "m"
			
			RETURN
			"
			<div style='width:100%;height:100%;background:#0B2540;border:1px solid #31597A;border-radius:8px;overflow:hidden;font-family:Segoe UI,Arial,sans-serif;color:#F8FAFC;box-sizing:border-box;'>
			<svg viewBox='0 0 1280 560' width='100%' height='100%' preserveAspectRatio='xMidYMid meet'>
			  <defs>
			    <filter id='shadow'><feDropShadow dx='0' dy='5' stdDeviation='5' flood-color='#000' flood-opacity='.28'/></filter>
			    <filter id='txt'><feDropShadow dx='0' dy='1' stdDeviation='1.4' flood-color='#071827' flood-opacity='.95'/></filter>
			    <linearGradient id='inflow' x1='0' x2='1'>
			      <stop stop-color='" & _Yellow & "' stop-opacity='.92'/>
			      <stop offset='1' stop-color='" & _Green & "' stop-opacity='.84'/>
			    </linearGradient>
			    <linearGradient id='profit' x1='0' x2='1'>
			      <stop stop-color='" & _Green & "' stop-opacity='.78'/>
			      <stop offset='1' stop-color='" & _Green & "' stop-opacity='.95'/>
			    </linearGradient>
			    <linearGradient id='cost' x1='0' x2='1'>
			      <stop stop-color='" & _Red & "' stop-opacity='.58'/>
			      <stop offset='1' stop-color='" & _Red & "' stop-opacity='.95'/>
			    </linearGradient>
			    <style>
			      .h{fill:#F8FAFC;font-size:24px;font-weight:800}
			      .s{fill:#8FB5D6;font-size:13px}
			      .k{font-size:11px;font-weight:800;letter-spacing:1.4px}
			      .ky{fill:" & _Yellow & "}
			      .kg{fill:" & _Green & "}
			      .l{fill:#F8FAFC;font-size:14px;font-weight:800;filter:url(#txt)}
			      .v{fill:#D8E0EA;font-size:12px;filter:url(#txt)}
			      .n{rx:2;filter:url(#shadow)}
			    </style>
			  </defs>
			
			  <rect width='1280' height='560' fill='#0B2540'/>
			  <text x='34' y='38' class='h'>Income to Outcomes Flow</text>
			  <text x='34' y='62' class='s'>Staged view: revenue streams to gross profit, operating costs and final result</text>
			
			  <text x='78' y='105' class='k ky'>REVENUE STREAMS</text>
			  <text x='360' y='105' class='k kg'>TOTAL REVENUE</text>
			  <text x='625' y='105' class='k kg'>GROSS SPLIT</text>
			  <text x='900' y='105' class='k kg'>OPERATING RESULT</text>
			
			  <path d='M145 145 C230 145 270 230 360 245' stroke='url(#inflow)' stroke-width='" & _BroadcastW & "' fill='none' stroke-linecap='round'/>
			  <path d='M145 205 C230 205 270 250 360 265' stroke='url(#inflow)' stroke-width='" & _CommercialW & "' fill='none' stroke-linecap='round'/>
			  <path d='M145 265 C230 265 270 270 360 285' stroke='url(#inflow)' stroke-width='" & _MatchdayW & "' fill='none' stroke-linecap='round'/>
			  <path d='M145 325 C230 325 270 295 360 305' stroke='url(#inflow)' stroke-width='" & _PlayerSalesW & "' fill='none' stroke-linecap='round'/>
			  <path d='M145 385 C230 385 270 320 360 325' stroke='url(#inflow)' stroke-width='" & _CompetitionW & "' fill='none' stroke-linecap='round'/>
			  <path d='M145 445 C230 445 270 345 360 345' stroke='url(#inflow)' stroke-width='" & _OtherIncomeW & "' fill='none' stroke-linecap='round'/>
			
			  <path d='M420 265 C505 265 555 185 650 185' stroke='url(#profit)' stroke-width='" & _GrossW & "' fill='none' stroke-linecap='round'/>
			  <path d='M420 305 C505 305 555 365 650 365' stroke='url(#cost)' stroke-width='" & _DirectW & "' fill='none' stroke-linecap='round'/>
			  <path d='M710 185 C795 185 840 140 930 140' stroke='url(#profit)' stroke-width='" & _BalanceW & "' fill='none' stroke-linecap='round'/>
			  <path d='M710 215 C795 215 840 285 930 305' stroke='url(#cost)' stroke-width='" & _OperatingW & "' fill='none' stroke-linecap='round'/>
			  <path d='M990 140 C1055 140 1085 95 1150 95' stroke='" & _BalanceColor & "' stroke-width='" & _BalanceW & "' fill='none' stroke-linecap='round' opacity='.9'/>
			
			  <rect class='n' x='126' y='124' width='22' height='42' fill='" & _Yellow & "'/>
			  <rect class='n' x='126' y='186' width='22' height='38' fill='" & _Yellow & "'/>
			  <rect class='n' x='126' y='250' width='22' height='30' fill='" & _Yellow & "'/>
			  <rect class='n' x='126' y='313' width='22' height='26' fill='" & _Yellow & "'/>
			  <rect class='n' x='126' y='374' width='22' height='24' fill='" & _Yellow & "'/>
			  <rect class='n' x='126' y='437' width='22' height='20' fill='" & _Yellow & "'/>
			
			  <rect class='n' x='360' y='220' width='60' height='140' fill='#666A6D'/>
			  <rect class='n' x='650' y='145' width='60' height='100' fill='" & _GrossColor & "'/>
			  <rect class='n' x='650' y='325' width='60' height='100' fill='" & _Red & "'/>
			  <rect class='n' x='930' y='112' width='60' height='70' fill='" & _BalanceColor & "'/>
			  <rect class='n' x='930' y='270' width='60' height='90' fill='" & _Red & "'/>
			  <rect class='n' x='1150' y='76' width='42' height='38' fill='" & _BalanceColor & "'/>
			
			  <text x='32' y='143' class='l'>Broadcast</text><text x='48' y='163' class='v'>£" & FORMAT(DIVIDE(_Broadcast,1000000), "#,##0") & "m</text>
			  <text x='25' y='204' class='l'>Commercial</text><text x='47' y='224' class='v'>£" & FORMAT(DIVIDE(_Commercial,1000000), "#,##0") & "m</text>
			  <text x='43' y='264' class='l'>Matchday</text><text x='55' y='284' class='v'>£" & FORMAT(DIVIDE(_Matchday,1000000), "#,##0") & "m</text>
			  <text x='25' y='324' class='l'>Player Sales</text><text x='54' y='344' class='v'>£" & FORMAT(DIVIDE(_PlayerSales,1000000), "#,##0") & "m</text>
			  <text x='12' y='384' class='l'>Competitions</text><text x='54' y='404' class='v'>£" & FORMAT(DIVIDE(_Competition,1000000), "#,##0") & "m</text>
			  <text x='40' y='444' class='l'>Other</text><text x='55' y='464' class='v'>£" & FORMAT(DIVIDE(_OtherIncome,1000000), "#,##0") & "m</text>
			
			  <text x='390' y='277' class='l' text-anchor='middle'>Revenue</text>
			  <text x='390' y='300' class='v' text-anchor='middle'>" & _FmtRevenue & "</text>
			
			  <text x='680' y='186' class='l' text-anchor='middle'>Gross Profit</text>
			  <text x='680' y='208' class='v' text-anchor='middle'>" & _FmtGross & "</text>
			
			  <text x='680' y='365' class='l' text-anchor='middle'>Direct Costs</text>
			  <text x='680' y='388' class='v' text-anchor='middle'>" & _FmtDirect & "</text>
			  <text x='725' y='348' class='v'>Players £" & FORMAT(DIVIDE(_WagesPlayers,1000000), "#,##0") & "m</text>
			  <text x='725' y='370' class='v'>Amort. £" & FORMAT(DIVIDE(_Amortisation,1000000), "#,##0") & "m</text>
			  <text x='725' y='392' class='v'>Agents £" & FORMAT(DIVIDE(_AgentFees,1000000), "#,##0") & "m</text>
			
			  <text x='960' y='137' class='l' text-anchor='middle'>Operating Balance</text>
			  <text x='960' y='160' class='v' text-anchor='middle'>" & _FmtBalance & "</text>
			
			  <text x='960' y='303' class='l' text-anchor='middle'>Operating Costs</text>
			  <text x='960' y='326' class='v' text-anchor='middle'>" & _FmtOperating & "</text>
			  <text x='1010' y='292' class='v'>Staff £" & FORMAT(DIVIDE(_WagesStaff,1000000), "#,##0") & "m</text>
			  <text x='1010' y='314' class='v'>Ops £" & FORMAT(DIVIDE(_Operations,1000000), "#,##0") & "m</text>
			  <text x='1010' y='336' class='v'>Academy + Mktg £" & FORMAT(DIVIDE(_Academy + _Marketing,1000000), "#,##0") & "m</text>
			
			  <text x='1205' y='91' class='l'>" & _BalanceLabel & "</text>
			  <text x='1205' y='112' class='v'>" & _FmtBalance & "</text>
			
			  <rect x='34' y='505' width='420' height='34' rx='17' fill='#071827' stroke='#31597A'/>
			  <circle cx='56' cy='522' r='6' fill='" & _Yellow & "'/><text x='70' y='526' class='v'>Revenue inflow</text>
			  <circle cx='198' cy='522' r='6' fill='" & _Green & "'/><text x='212' y='526' class='v'>Profit flow</text>
			  <circle cx='325' cy='522' r='6' fill='" & _Red & "'/><text x='339' y='526' class='v'>Cost outflow</text>
			</svg>
			</div>
			"
		displayFolder: 7_Visuals
		lineageTag: 435a6f18-fed0-4442-a777-8ea256426c9e

	measure '$ Transfer Fee Paid (£)' =
			
			CALCULATE(
			    SUM(fact_transfers[transfer_fee_gbp]),
			    fact_transfers[direction] = "IN",
			    fact_transfers[loan] = FALSE()
			)
		formatString: "£"#,0;-"£"#,0;"£"#,0
		displayFolder: 3_Transfers\$
		lineageTag: 8f5d3d6a-b998-4e0b-8b3d-2b065a39f684

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure '$ Player Latest Market Value (£)' =
			
			VAR _LatestDate =
			    CALCULATE(
			        MAX(fact_player_valuations[valuation_date]),
			        REMOVEFILTERS(dim_season)
			    )
			RETURN
			    CALCULATE(
			        MAX(fact_player_valuations[market_value_gbp]),
			        REMOVEFILTERS(dim_season),
			        fact_player_valuations[valuation_date] = _LatestDate
			    )
		formatString: "£"#,0;-"£"#,0;"£"#,0
		displayFolder: 3_Transfers\$
		lineageTag: e2f2fc2c-4468-4d77-b8b6-9c7e45a0bbd3

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure '% Player Transfer ROI' =
			
			DIVIDE(
			    [$ Player Latest Market Value (£)] - [$ Transfer Fee Paid (£)],
			    [$ Transfer Fee Paid (£)]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 3_Transfers\%
		lineageTag: a96a2f6f-cd4d-4e16-85bf-f31d47218967

	measure 'REF Transfer ROI Quadrant' =
			
			VAR _Fee = [$ Transfer Fee Paid (£)]
			VAR _ROI = [% Player Transfer ROI]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(_Fee) || _Fee = 0, "Free / Academy",
			        ISBLANK(_ROI), "No valuation",
			        _ROI >= 0.15, "Value Creator",
			        _ROI <= -0.15, "Value Destroyer",
			        "Neutral"
			    )
		displayFolder: 3_Transfers\REF
		lineageTag: 0ddc2b06-6bbb-4dd1-997f-3d61d8b35f5b

	measure 'REF Transfer ROI Bar Color' =
			
			SWITCH(
			    [REF Transfer ROI Quadrant],
			    "Value Creator", "#59A472",
			    "Value Destroyer", "#E63535",
			    "Neutral", "#C8A84B",
			    "Free / Academy", "#59A472",
			    "#8FB5D6"
			)
		displayFolder: 3_Transfers\REF
		lineageTag: a2861d67-5212-48eb-8ef0-ff686b3bb140

	measure 'REF Wage Efficiency Band' =
			
			VAR _WagePerAppearance = [$ Wage per Appearance (£)]
			VAR _Appearances = [# Total Appearances]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(_Appearances) || _Appearances = 0, "No appearances",
			        _WagePerAppearance >= 1500000, "Red flag",
			        _WagePerAppearance >= 750000, "Monitor",
			        "Efficient"
			    )
		displayFolder: 4_Wages\REF
		lineageTag: 5df1a6fd-3d89-4ab4-b67d-a262a169b910

	measure 'REF Wage Efficiency Color' =
			
			SWITCH(
			    [REF Wage Efficiency Band],
			    "Red flag", "#E63535",
			    "Monitor", "#C8A84B",
			    "Efficient", "#59A472",
			    "No appearances", "#8FB5D6",
			    "#8FB5D6"
			)
		displayFolder: 4_Wages\REF
		lineageTag: 38809f9d-4372-4135-b879-f7a2badc7aa6

	measure '# Wage Efficiency Rank' =
			
			RANKX(
			    ALLSELECTED(dim_player[player_name]),
			    [$ Wage per Appearance (£)],
			    ,
			    DESC,
			    Dense
			)
		formatString: 0
		displayFolder: 4_Wages\Efficiency
		lineageTag: d7ad775b-24aa-4ca4-a9b0-834f24553e60

	measure '$ Wage per Appearance 6-Season Avg (£)' =
			
			AVERAGEX(
			    ALLSELECTED(dim_season[season_label]),
			    [$ Wage per Appearance (£)]
			)
		displayFolder: 4_Wages\$
		lineageTag: b1f31dda-9a65-4faf-85fc-40a8a3a471b7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'REF Wage per Appearance Season Color' =
			
			VAR _Current = [$ Wage per Appearance (£)]
			VAR _Avg =
			    AVERAGEX(
			        ALLSELECTED(dim_season[season_label]),
			        [$ Wage per Appearance (£)]
			    )
			VAR _Delta = DIVIDE(_Current - _Avg, _Avg)
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(_Current), "#8FB5D6",
			        _Delta > 0.10, "#E63535",
			        _Delta >= -0.10, "#C8A84B",
			        "#59A472"
			    )
		displayFolder: 4_Wages\REF
		lineageTag: 7b454fb7-eebf-4e2a-8a22-6069d62c19e3

	measure 'REF Wage Efficiency Trend Color' =
			
			VAR _Current = [$ Wage per Appearance (£)]
			VAR _Avg =
			    CALCULATE(
			        AVERAGEX(
			            VALUES(dim_season[season_label]),
			            [$ Wage per Appearance (£)]
			        ),
			        ALLSELECTED(dim_season)
			    )
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(_Current), "#8FB5D6",
			        _Current > _Avg, "#E63535",
			        "#59A472"
			    )
		displayFolder: 4_Wages\REF
		lineageTag: 7f2efc89-196c-4a8a-8277-0c5781978a10

	measure '$ Median Transfer Fee Paid (£)' =
			
			MEDIANX(
			    FILTER(
			        ALLSELECTED(dim_player[player_name]),
			        NOT ISBLANK([$ Transfer Fee Paid (£)]) &&
			            [$ Transfer Fee Paid (£)] > 0
			    ),
			    [$ Transfer Fee Paid (£)]
			)
		formatString: 0
		displayFolder: 3_Transfers\$
		lineageTag: 52d22bdc-a525-4ac5-9eac-a23171ee3b76

	measure '$ Median Player Market Value (£)' =
			
			MEDIANX(
			    FILTER(
			        ALLSELECTED(dim_player[player_name]),
			        NOT ISBLANK([$ Player Latest Market Value (£)])
			    ),
			    [$ Player Latest Market Value (£)]
			)
		formatString: 0
		displayFolder: 3_Transfers\$
		lineageTag: 1c159f7c-4895-4323-9732-c419a77c4103

	measure '# xG For' =
			
			SUM(fact_matches[xg_for])
		formatString: 0.0
		displayFolder: 1_Matches\#
		lineageTag: 3919d69b-c42b-4c85-a380-7f955505fd5d

	measure '# xG Against' =
			
			SUM(fact_matches[xg_against])
		formatString: 0.0
		displayFolder: 1_Matches\#
		lineageTag: eed5aefe-d9f8-41bc-82dc-9f94f6400f5b

	measure '# xG Difference' = [# xG For] - [# xG Against]
		formatString: 0.0
		displayFolder: 1_Matches\#
		lineageTag: 51680a4b-3486-4978-b695-32e664e093fe

	measure '# Player Master Records' =
			
			DISTINCTCOUNT(dim_player[player_id])
		formatString: 0
		displayFolder: 0_General
		lineageTag: 15c816b2-15b8-4ae6-85f3-0b9e509f2021

	measure '# Players in Latest Valuation Snapshot' =
			
			VAR _LatestDate =
			    MAX(fact_player_valuations[valuation_date])
			RETURN
			    IF(
			        ISINSCOPE(fact_player_valuations[valuation_date]) ||
			            HASONEVALUE(fact_player_valuations[valuation_date]),
			        DISTINCTCOUNT(fact_player_valuations[player_id]),
			        CALCULATE(
			            DISTINCTCOUNT(fact_player_valuations[player_id]),
			            fact_player_valuations[valuation_date] = _LatestDate
			        )
			    )
		formatString: 0
		displayFolder: 5_Squad_Value\#
		lineageTag: 593f2603-9895-4488-a21e-cc055a586457

	column Column
		isHidden
		formatString: 0
		displayFolder: 0_General
		lineageTag: f8960f0e-a5eb-422d-b259-28384938467c
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'DAX Measures' = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = ceaac7a97767417e83db8b3b1b7c47bb

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

