table dim_product
	lineageTag: f5a17aa0-5f4b-4bcb-8a94-b9edde0b78dd

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: fc4311a7-1875-479a-9d1e-7df3ecc98121
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 78adf927-558a-4b89-b7a0-f7c58f26e37c
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column ProductNumber
		dataType: string
		lineageTag: 32b057ab-f5bc-4dc1-a3db-fabfa166e9db
		summarizeBy: none
		sourceColumn: ProductNumber

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: d1a36e91-1ac2-4bf4-833e-7e60a2ce46fd
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		lineageTag: f2a8ae35-5137-48c6-ba19-d5815b724da0
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column ProductLine
		dataType: string
		lineageTag: 0163f833-538a-4b8c-8094-98b2c7323055
		summarizeBy: none
		sourceColumn: ProductLine

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: 26264bc9-d804-49e4-a671-7a2f6864bf07
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column StandardCost
		dataType: double
		lineageTag: 062d61c3-e785-454f-a5ba-57e7033e83b3
		summarizeBy: none
		sourceColumn: StandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ListPrice
		dataType: double
		lineageTag: 6a2a2832-348c-407a-a993-5fe6829d5155
		summarizeBy: none
		sourceColumn: ListPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition dim_product = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\cristian.perez\Documents\Cristian Personal\Git\repositorio personal\cl-data-analyst-portfolio\03-regional-sales-performance\docs\dim_product.csv"), [Delimiter = ",", Columns = 9, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"ProductID", Int64.Type}, {"ProductName", type text}, {"ProductNumber", type text}, {"Category", type text}, {"Subcategory", type text}, {"ProductLine", type text}, {"Color", type text}, {"StandardCost", type number}, {"ListPrice", type number}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

