table dim_channel
	lineageTag: 38789683-0c54-4408-ae9a-ca312aa3df54

	column ChannelKey
		dataType: int64
		formatString: 0
		lineageTag: fc7ec1a5-501a-48a8-af19-08f3af0df1a1
		summarizeBy: none
		sourceColumn: ChannelKey

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		lineageTag: 09269192-2a98-4012-aa66-f5a8d164a01e
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	partition dim_channel = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\cristian.perez\Documents\Cristian Personal\Git\repositorio personal\cl-data-analyst-portfolio\03-regional-sales-performance\docs\dim_channel.csv"), [Delimiter = ",", Columns = 2, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"ChannelKey", Int64.Type}, {"Channel", type text}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

